const Arrow = () => <svg viewBox="0 0 20 20" aria-hidden="true"><path d="M4 10h11M11 5l5 5-5 5" /></svg>;

export default function SiteFooter(){const urgentEmail='mailto:Hello@TaxEnquiryHelp.co.uk?subject=Urgent%20HMRC%20enquiry%20%E2%80%93%20response%20deadline&body=Hello%20TaxEnquiryHelp%2C%0D%0A%0D%0APlease%20review%20my%20urgent%20HMRC%20enquiry.%0D%0A%0D%0AFull%20name%3A%20%0D%0AContact%20number%3A%20%0D%0AType%20of%20HMRC%20enquiry%3A%20%0D%0ADate%20of%20HMRC%20letter%3A%20%0D%0AResponse%20deadline%3A%20%0D%0ABrief%20summary%3A%20%0D%0A%0D%0APlease%20do%20not%20include%20your%20UTR%2C%20National%20Insurance%20number%20or%20sensitive%20documents%20in%20this%20initial%20email.';return <footer className="site-footer">
  <div className="footer-top">
    <div><a className="footer-brand footer-logo-link" href="/" aria-label="TaxEnquiryHelp home"><img className="footer-logo protected-logo" src="/tax-enquiry-help-logo.png" width="724" height="191" alt="Tax Enquiry Help — expert support, clear answers, peace of mind" draggable="false" /></a><p>Clear, confidential support for HMRC tax enquiries across the UK.</p><p className="powered-by">TaxEnquiryHelp is powered by <strong>Mayfair Accountants and wealth Advisors</strong></p></div>
    <div><h2>Enquiry support</h2><a href="/knowledge-base/hmrc-self-assessment-enquiry-guide">Self Assessment enquiries</a><a href="/knowledge-base/what-is-an-hmrc-compliance-check">HMRC compliance checks</a><a href="/knowledge-base#business">VAT &amp; PAYE enquiries</a><a href="/knowledge-base/appeal-hmrc-tax-penalty">Tax penalties &amp; appeals</a></div>
    <div><h2>Helpful links</h2><a href="/hmrc-problems">HMRC Problems</a><a href="/industries">Industries</a><a href="/knowledge-base">Knowledge Hub</a><a href="/faqs">FAQs</a><a href="/contact">Contact</a></div>
    <div><h2>Need help?</h2><p>Start with a confidential, no-obligation conversation.</p><a className="footer-link" href="/contact">Make an enquiry <Arrow /></a><p className="footer-urgent">Urgent enquiry?</p><a className="footer-email" href={urgentEmail}>Hello@TaxEnquiryHelp.co.uk</a></div>
  </div>
  <div className="footer-bottom"><span>© 2026 TaxEnquiryHelp</span><div><a href="/privacy">Privacy</a><a href="/cookies">Cookies</a><a href="/terms">Terms</a></div></div>
  <p className="disclaimer">TaxEnquiryHelp provides general information and may connect users with independent tax professionals. Content on this website is not tax, legal or financial advice. Adviser qualifications, regulatory status, fees and engagement terms should be confirmed directly before instruction.</p>
</footer>}
