import type { Metadata } from 'next';
import LegalPage,{LegalSection} from '../components/LegalPage';
import '../legal.css';

export const metadata:Metadata={title:'Privacy Notice | TaxEnquiryHelp',description:'How TaxEnquiryHelp collects, uses, shares, secures and retains personal information under UK data protection law.',alternates:{canonical:'/privacy'}};

export default function Privacy(){return <LegalPage eyebrow="UK GDPR privacy information" title="Privacy notice" intro="This notice explains how personal information is handled when you visit TaxEnquiryHelp, submit an enquiry or communicate with us. It also explains how information may be shared with an independent professional firm selected to provide services for your requirements.">
  <LegalSection number="01" title="Who is responsible for your information"><p>The organisation operating TaxEnquiryHelp is the data controller for information collected through this website until it is lawfully transferred to or collected directly by an independent professional firm. That firm will normally become a separate controller for the information it uses to assess, accept and deliver professional services.</p><div className="legal-placeholder"><strong>Complete before launch:</strong> insert the operator’s full registered name, company number, registered office, ICO registration number, privacy email and data-protection contact. Confirm whether Mayfair Accountants and wealth Advisors is the controller, a trading style or a separate entity.</div></LegalSection>
  <LegalSection number="02" title="Information we collect"><p>We may collect information you provide in forms, calls and correspondence, including your name, email address, telephone number, enquiry category, HMRC deadline and description of the matter. We also process ordinary technical information needed to secure and operate the website.</p><p>Tax matters can reveal financial information and may incidentally reveal special-category or criminal-offence information. Do not provide a Unique Taxpayer Reference, National Insurance number, Government Gateway credentials, bank credentials or unrequested documents through an initial website form.</p></LegalSection>
  <LegalSection number="03" title="Why we use information and our lawful bases"><table className="legal-table"><thead><tr><th>Purpose</th><th>Likely lawful basis</th></tr></thead><tbody><tr><td>Responding to your enquiry and taking steps you request before a possible engagement</td><td>Steps at your request before entering a contract; legitimate interests where appropriate</td></tr><tr><td>Matching the enquiry to a suitable independent professional firm</td><td>Your requested pre-contract steps and/or legitimate interests in providing an effective referral service</td></tr><tr><td>Operating, securing and improving the website</td><td>Legitimate interests in service security, fraud prevention and performance</td></tr><tr><td>Meeting legal, regulatory, tax, record-keeping and anti-money-laundering obligations</td><td>Legal obligation; substantial public-interest conditions where applicable</td></tr><tr><td>Optional marketing</td><td>Consent where required by PECR and UK data protection law</td></tr></tbody></table><p>The final operator must document its lawful-basis assessment and any additional condition required before processing special-category or criminal-offence data.</p></LegalSection>
  <LegalSection number="04" title="Independent professional firms"><div className="legal-callout"><p><strong>Important service distinction:</strong> TaxEnquiryHelp may route your enquiry to an independent accountancy, tax advisory or legal firm chosen according to the type, complexity, location, availability and expertise required. Any tax, accountancy, legal or representation service will be provided by that individual firm under its own engagement letter, terms, fees, privacy notice, complaints procedure and professional responsibilities.</p></div><p>We will share only information reasonably needed for the firm to assess your enquiry, unless law requires otherwise. You should review the selected firm’s identity, qualifications, regulatory or professional-body status and engagement terms before instruction.</p></LegalSection>
  <LegalSection number="05" title="Who receives information"><p>Recipients may include website hosting and security providers, form or CRM providers, professional advisers, insurers, fraud-prevention services, regulators, law-enforcement bodies and the independent firm approached about your enquiry. Suppliers acting on our instructions must be subject to appropriate data-processing terms.</p><p>We do not sell personal information. A commercial referral arrangement or fee, if applicable, should be disclosed transparently before or when the introduction is made.</p></LegalSection>
  <LegalSection number="06" title="International transfers"><p>If a technology supplier stores or accesses information outside the United Kingdom, the controller must use a lawful transfer mechanism and appropriate safeguards, such as UK adequacy regulations or approved contractual safeguards, and provide information about how to obtain a copy.</p><div className="legal-placeholder"><strong>Complete before launch:</strong> audit hosting, CRM, email, analytics, backup and support locations and list the applicable transfer safeguards.</div></LegalSection>
  <LegalSection number="07" title="How long we keep information"><p>Personal information should be retained only for as long as necessary for the enquiry, legal obligations, complaints, fraud prevention and establishment or defence of legal claims. Enquiries that do not proceed should have a defined shorter retention period; client files held by an engaged firm will follow that firm’s separate retention policy.</p><div className="legal-placeholder"><strong>Complete before launch:</strong> approve specific retention periods for abandoned forms, unsuccessful referrals, correspondence, consent records, security logs and complaints.</div></LegalSection>
  <LegalSection number="08" title="Your data-protection rights"><p>Depending on the processing and lawful basis, you may have rights to be informed, access your information, correct inaccurate data, request erasure, restrict processing, receive portable data, object to processing and withdraw consent. You also have the right to object to direct marketing at any time.</p><p>Requests should be sent to the final privacy contact. Identity may need to be verified without requesting disproportionate information. You may complain to the Information Commissioner’s Office at <a href="https://ico.org.uk/make-a-complaint/" rel="external">ico.org.uk</a>.</p></LegalSection>
  <LegalSection number="09" title="Security, children and automated decisions"><p>Appropriate technical and organisational measures should protect information in transit and at rest, restrict staff access and manage incidents. No internet transmission is completely secure. This service is intended for adults and is not directed at children.</p><p>TaxEnquiryHelp does not currently make solely automated decisions producing legal or similarly significant effects. Routing questions may help categorise an enquiry, but professional acceptance and advice require human assessment.</p></LegalSection>
  <LegalSection number="10" title="Changes and contact"><p>This notice should be reviewed whenever the service model, technology, recipients or law changes. Material changes should be brought to users’ attention. Contact details for privacy questions and rights requests must be inserted before live collection begins.</p></LegalSection>
</LegalPage>}
