import type { Metadata } from 'next';
import LegalPage,{LegalSection} from '../components/LegalPage';
import '../legal.css';

export const metadata:Metadata={title:'Privacy Notice | TaxEnquiryHelp',description:'Read how TaxEnquiryHelp collects, uses, shares, protects and retains personal information under UK GDPR and UK data protection law.',alternates:{canonical:'/privacy'}};

export default function Privacy(){return <LegalPage eyebrow="UK GDPR privacy information" title="Privacy notice" intro="This notice explains how personal information is handled when you visit TaxEnquiryHelp, submit an enquiry or communicate with TaxEnquiryHelp. It also explains how information may be shared with an independent professional firm selected to provide services for your requirements.">
  <LegalSection number="01" title="Who is responsible for your information"><p>TaxEnquiryHelp is the data controller for personal information collected through this website until that information is lawfully transferred to, or collected directly by, an independent professional firm. That firm will normally become a separate controller for the information it uses to assess, accept and deliver professional services.</p><p>Privacy enquiries and data-protection requests may be sent to <a href="mailto:Hello@TaxEnquiryHelp.co.uk">Hello@TaxEnquiryHelp.co.uk</a> or by post to TaxEnquiryHelp, Devonshire House, Level 1, One Mayfair Place, Mayfair, London, England, W1J 8AJ.</p></LegalSection>
  <LegalSection number="02" title="Information TaxEnquiryHelp collects"><p>TaxEnquiryHelp may collect information you provide in forms, calls and correspondence, including your name, email address, telephone number, enquiry category, HMRC deadline and description of the matter. TaxEnquiryHelp also processes ordinary technical information needed to secure and operate the website.</p><p>Tax matters can reveal financial information and may incidentally reveal special-category or criminal-offence information. Do not provide a Unique Taxpayer Reference, National Insurance number, Government Gateway credentials, bank credentials or unrequested documents through an initial website form.</p></LegalSection>
  <LegalSection number="03" title="Why we use information and our lawful bases"><table className="legal-table"><thead><tr><th>Purpose</th><th>Lawful basis</th></tr></thead><tbody><tr><td>Responding to your enquiry and taking steps you request before a possible engagement</td><td>Steps at your request before entering a contract; legitimate interests where appropriate</td></tr><tr><td>Matching the enquiry to a suitable independent professional firm</td><td>Your requested pre-contract steps and/or legitimate interests in providing an effective referral service</td></tr><tr><td>Operating, securing and improving the website</td><td>Legitimate interests in service security, fraud prevention and performance</td></tr><tr><td>Meeting legal, regulatory, tax, record-keeping and anti-money-laundering obligations</td><td>Legal obligation; substantial public-interest conditions where applicable</td></tr><tr><td>Optional marketing</td><td>Consent where required by PECR and UK data protection law</td></tr></tbody></table><p>Where information includes special-category or criminal-offence data, TaxEnquiryHelp will process it only where an additional condition under UK data-protection law applies.</p></LegalSection>
  <LegalSection number="04" title="Independent professional firms"><div className="legal-callout"><p><strong>Important service distinction:</strong> TaxEnquiryHelp may route your enquiry to an independent accountancy, tax advisory or legal firm chosen according to the type, complexity, location, availability and expertise required. Any tax, accountancy, legal or representation service will be provided by that individual firm under its own engagement letter, terms, fees, privacy notice, complaints procedure and professional responsibilities.</p></div><p>TaxEnquiryHelp will share only information reasonably needed for the firm to assess your enquiry, unless law requires otherwise. You should review the selected firm’s identity, qualifications, regulatory or professional-body status and engagement terms before instruction.</p></LegalSection>
  <LegalSection number="05" title="Who receives information"><p>Recipients may include website hosting and security providers, form or CRM providers, professional advisers, insurers, fraud-prevention services, regulators, law-enforcement bodies and the independent firm approached about your enquiry. Suppliers acting on TaxEnquiryHelp’s instructions must be subject to appropriate data-processing terms.</p><p>TaxEnquiryHelp does not sell personal information. Where a commercial referral arrangement or fee applies, TaxEnquiryHelp will disclose relevant information transparently before or when the introduction is made.</p></LegalSection>
  <LegalSection number="06" title="International transfers"><p>Some technology suppliers may store or access information outside the United Kingdom. Where this occurs, TaxEnquiryHelp uses suppliers that provide an appropriate lawful transfer mechanism, such as UK adequacy regulations, the UK International Data Transfer Agreement or the UK Addendum to approved standard contractual clauses, together with appropriate safeguards.</p><p>You may contact TaxEnquiryHelp for more information about the safeguards relevant to your information.</p></LegalSection>
  <LegalSection number="07" title="How long we keep information"><p>TaxEnquiryHelp keeps personal information only for as long as reasonably necessary to respond to and route an enquiry, meet legal obligations, handle complaints, prevent fraud and establish or defend legal claims. Enquiries that do not proceed are deleted or anonymised when they are no longer needed for those purposes.</p><p>Client files held by an independent firm are subject to that firm’s separate retention policy. Security logs and consent records may be retained for different periods where needed to protect the service or demonstrate compliance.</p></LegalSection>
  <LegalSection number="08" title="Your data-protection rights"><p>Depending on the processing and lawful basis, you may have rights to be informed, access your information, correct inaccurate data, request erasure, restrict processing, receive portable data, object to processing and withdraw consent. You also have the right to object to direct marketing at any time.</p><p>Send requests to <a href="mailto:Hello@TaxEnquiryHelp.co.uk">Hello@TaxEnquiryHelp.co.uk</a>. TaxEnquiryHelp may need to verify your identity without requesting disproportionate information. You may complain to the Information Commissioner’s Office at <a href="https://ico.org.uk/make-a-complaint/" rel="external">ico.org.uk</a>.</p></LegalSection>
  <LegalSection number="09" title="Security, children and automated decisions"><p>TaxEnquiryHelp uses appropriate technical and organisational measures designed to protect information, restrict access and manage incidents. No internet transmission is completely secure. TaxEnquiryHelp is intended for adults and is not directed at children.</p><p>TaxEnquiryHelp does not currently make solely automated decisions producing legal or similarly significant effects. Routing questions may help categorise an enquiry, but professional acceptance and advice require human assessment.</p></LegalSection>
  <LegalSection number="10" title="Changes and contact"><p>TaxEnquiryHelp may update this notice when its services, technology, recipients or the law change. Material changes will be highlighted on the website and the date at the top of this notice will be revised.</p><p>For privacy questions or rights requests, email <a href="mailto:Hello@TaxEnquiryHelp.co.uk">Hello@TaxEnquiryHelp.co.uk</a> or use the <a href="/contact">Contact page</a>.</p></LegalSection>
</LegalPage>}
