import type { Metadata } from 'next';
import LegalPage,{LegalSection} from '../components/LegalPage';
import '../legal.css';

export const metadata:Metadata={title:'Website Terms | TaxEnquiryHelp',description:'Terms governing use of TaxEnquiryHelp, its HMRC enquiry information, referral service and independent professional firm introductions.',alternates:{canonical:'/terms'}};

export default function Terms(){return <LegalPage eyebrow="Website and referral terms" title="Website terms" intro="These terms govern your use of TaxEnquiryHelp, its educational content, enquiry-routing tools and introductions to independent professional firms.">
  <LegalSection number="01" title="About these terms"><p>By using this website, you agree to these terms. They do not replace the engagement letter or terms of any accountant, tax adviser, solicitor or other professional you instruct. If you do not agree, do not submit an enquiry or rely on the website.</p><div className="legal-placeholder"><strong>Complete before launch:</strong> add the operator’s legal name, company number, registered office, contact details, VAT status and governing-law review.</div></LegalSection>
  <LegalSection number="02" title="Information, not tax or legal advice"><p>Articles, FAQs, forms and automated pathways provide general educational information. They do not consider all facts, do not constitute tax, legal, financial or investment advice, and do not create a professional relationship. HMRC guidance, tax law and procedure change.</p><p>Do not delay a filing, payment, appeal or HMRC response because you are reading the website or awaiting an introduction. Obtain advice about the precise notice and deadline.</p></LegalSection>
  <LegalSection number="03" title="Independent firms provide professional services"><div className="legal-callout"><p><strong>TaxEnquiryHelp does not itself promise to provide the underlying tax, accountancy, legal or representation service.</strong> Services will be provided by the individual independent firm selected according to the enquiry’s requirements and only after that firm accepts the matter and issues its own engagement terms.</p></div><p>The selected firm is responsible for its advice, work, fees, conflicts checks, client verification, regulatory and professional obligations, complaints process and insurance. Check its legal identity, qualifications, professional-body or regulatory status and scope before instruction. An introduction does not guarantee acceptance, availability, a particular adviser or any outcome.</p></LegalSection>
  <LegalSection number="04" title="Enquiry routing and commercial arrangements"><p>Information you submit may be used to categorise the matter and approach a firm with relevant experience. Matching is not an endorsement or ranking of every available adviser. Factors may include subject, complexity, location, capacity and declared expertise.</p><p>TaxEnquiryHelp or an associated business may receive a referral fee or other commercial benefit where permitted. The final operating model should disclose the nature of any arrangement transparently and ensure it does not compromise the client’s interests.</p></LegalSection>
  <LegalSection number="05" title="Professional standards and client checks"><p>Firms dealing with HMRC are expected to comply with applicable law and the HMRC standard for agents. Depending on the service, a firm may also follow professional-body rules and anti-money-laundering requirements.</p><p>Before accepting work, a firm may require identity, ownership, source-of-funds or other verification and may be unable to explain certain actions where law restricts disclosure. Never share Government Gateway or GOV.UK One Login credentials with an adviser; use authorised agent processes.</p></LegalSection>
  <LegalSection number="06" title="Your responsibilities"><ul><li>Provide accurate, complete and timely information.</li><li>Do not omit facts because they appear unfavourable.</li><li>Preserve original documents and never fabricate or alter evidence.</li><li>Monitor and meet HMRC, tribunal, filing and payment deadlines unless a firm confirms responsibility in writing.</li><li>Review all engagement terms, advice and submissions before approval.</li><li>Keep login credentials, tax references and financial data secure.</li></ul></LegalSection>
  <LegalSection number="07" title="Fees, estimates and payment"><p>Using the website may be free, but independent firms charge under their own engagement terms. Any initial indication is not a fixed quote unless expressly stated by the firm. Fees can change if scope, records, urgency or complexity changes.</p><p>Tax liabilities, interest, penalties and HMRC payments are separate from professional fees. No website statement guarantees reduction, settlement or cancellation.</p></LegalSection>
  <LegalSection number="08" title="No guaranteed outcome"><p>Tax enquiries involve evidence, law and HMRC or tribunal decisions. Neither TaxEnquiryHelp nor an introduced firm can guarantee closure, penalty mitigation, tax savings, appeal success or a timeframe. Testimonials or examples, if later added, must not be treated as promises.</p></LegalSection>
  <LegalSection number="09" title="Acceptable use and intellectual property"><p>You may use the website for lawful personal or internal business purposes. You must not interfere with security, submit unlawful or misleading material, scrape at unreasonable scale, impersonate another person or use content to facilitate tax evasion or fraud.</p><p>Website branding, original text, design and code are protected by applicable intellectual-property rights. Limited quotation with attribution is permitted where law allows; substantial reproduction requires permission.</p></LegalSection>
  <LegalSection number="10" title="Availability, links and liability"><p>We aim for accurate and available content but do not promise uninterrupted access or that every error will be corrected immediately. External links are provided for context and do not transfer responsibility for third-party content.</p><p>Nothing excludes liability that cannot legally be excluded, including liability for fraud or fraudulent misrepresentation. Any further limitations must be drafted for the confirmed operator, consumer/business audience and service model, and reviewed by a UK solicitor before launch.</p></LegalSection>
  <LegalSection number="11" title="Complaints"><p>Website or introduction complaints should first be sent through the <a href="/contact">Contact page</a>. Complaints about professional services must be directed to the firm that supplied them under its complaints procedure. The firm should explain any escalation route to a professional body, regulator, ombudsman or court that applies.</p></LegalSection>
  <LegalSection number="12" title="Governing law and changes"><p>These terms may be updated for changes in law, technology or services. The governing-law and jurisdiction clause must be confirmed after legal review, taking account of mandatory consumer protections and the final operator’s location.</p></LegalSection>
</LegalPage>}
