import type { Metadata } from 'next';
import LegalPage,{LegalSection} from '../components/LegalPage';
import '../legal.css';

export const metadata:Metadata={title:'Cookie Notice | TaxEnquiryHelp',description:'How TaxEnquiryHelp uses cookies and similar storage technologies and how users can manage their choices.',alternates:{canonical:'/cookies'}};

export default function Cookies(){return <LegalPage eyebrow="PECR and storage technologies" title="Cookie notice" intro="This notice explains cookies and similar technologies used by TaxEnquiryHelp, why they may be used and the choices available to you.">
  <LegalSection number="01" title="What cookies and similar technologies are"><p>Cookies are small files stored on a device. Similar technologies include local storage, tracking pixels, software development kits, device identifiers and techniques that access or store information on a device. UK rules can apply to the technology even where the information is not directly identifying.</p></LegalSection>
  <LegalSection number="02" title="TaxEnquiryHelp’s current approach"><div className="legal-callout"><p>TaxEnquiryHelp does not use advertising cookies or behavioural profiling. Essential technologies may be used for security, network delivery, load balancing and operation of requested website features.</p></div><p>TaxEnquiryHelp does not activate non-essential analytics, advertising, embedded media, chat or conversion technologies unless the consent required by UK law has first been obtained. TaxEnquiryHelp will update this notice if the technologies used by the website materially change.</p></LegalSection>
  <LegalSection number="03" title="Cookie categories"><table className="legal-table"><thead><tr><th>Category</th><th>Purpose</th><th>Consent</th></tr></thead><tbody><tr><td>Strictly necessary</td><td>Security, network delivery and functionality explicitly requested by the user</td><td>Usually exempt, but users must still receive clear information</td></tr><tr><td>Preferences</td><td>Remembering optional interface or language choices</td><td>Consent may be required depending on necessity</td></tr><tr><td>Analytics</td><td>Measuring visits, navigation and performance</td><td>Do not activate unless the applicable consent or statutory exemption is confirmed</td></tr><tr><td>Marketing</td><td>Advertising, cross-site tracking and campaign attribution</td><td>Prior, specific consent required</td></tr><tr><td>Third-party media</td><td>Maps, videos, chat or social embeds</td><td>May require consent before loading</td></tr></tbody></table></LegalSection>
  <LegalSection number="04" title="Consent and your choices"><p>Where consent is required, it must be freely given, specific, informed and indicated by a clear positive action. Rejecting non-essential technologies will be as straightforward as accepting them. Continuing to browse is not treated as consent.</p><p>TaxEnquiryHelp does not currently activate technologies requiring cookie consent. If that changes, TaxEnquiryHelp will provide a visible way to make, revisit and withdraw cookie choices. Withdrawal will not affect processing that occurred lawfully before it.</p></LegalSection>
  <LegalSection number="05" title="Technologies currently used"><table className="legal-table"><thead><tr><th>Provider or technology</th><th>Purpose</th><th>Category</th></tr></thead><tbody><tr><td>TaxEnquiryHelp website and hosting infrastructure</td><td>Delivering pages, protecting the service, balancing network traffic and processing requested form functions</td><td>Strictly necessary</td></tr></tbody></table><p>TaxEnquiryHelp does not currently use advertising, cross-site tracking or behavioural-profiling cookies. Hosting and security providers may process limited technical data, such as IP address, browser information and request logs, to deliver and protect the website; this does not mean that a cookie is necessarily stored on your device.</p></LegalSection>
  <LegalSection number="06" title="Browser controls and consequences"><p>Browsers allow you to block or delete stored information. Blocking strictly necessary technology may prevent secure forms or requested functionality from working. Browser controls do not replace the site’s duty to obtain consent where required.</p></LegalSection>
  <LegalSection number="07" title="Updates and complaints"><p>TaxEnquiryHelp will update this notice when its technology or applicable legal requirements change. Send questions to <a href="mailto:Hello@TaxEnquiryHelp.co.uk">Hello@TaxEnquiryHelp.co.uk</a> or through the <a href="/contact">Contact page</a>. Concerns about information rights can also be raised with the Information Commissioner’s Office.</p></LegalSection>
</LegalPage>}
