import {phase4Problems} from './phase4-problems';

export type ProblemPage = {
  slug: string;
  category: 'Letters and requests' | 'Return errors' | 'Penalties' | 'Income and evidence' | 'Property and disclosures' | 'Business tax checks';
  title: string;
  description: string;
  directAnswer: string;
  enquiryCategory: string;
  enquiryDetail?: string;
  relatedQuestion?: { title: string; href: string };
  canonicalGuide: { title: string; href: string };
  sections: { title: string; paragraphs: string[]; bullets?: string[] }[];
  actions: string[];
  records: string[];
  example: { title: string; paragraphs: string[] };
  faqs: [string, string][];
  sources: [string, string][];
};

const initialProblems: ProblemPage[] = [
  {
    slug: 'hmrc-nudge-letter',
    category: 'Letters and requests',
    title: 'HMRC Nudge Letter: What It Means and What to Do Next',
    description: 'Received an HMRC nudge letter? Understand why HMRC may have written, what to check, whether disclosure is required and how to respond accurately.',
    directAnswer: 'An HMRC nudge letter usually asks a taxpayer to check a particular part of their tax position and correct or disclose anything that is wrong. It is not automatically a formal enquiry or proof of an error, but it should not be ignored. Identify the issue, deadline and requested action, reconcile the figures and respond through the route stated in the letter.',
    enquiryCategory: 'compliance-check',
    canonicalGuide: { title: 'What is an HMRC compliance check?', href: '/knowledge-base/what-is-an-hmrc-compliance-check' },
    sections: [
      { title: 'What is an HMRC nudge letter?', paragraphs: ['“Nudge letter” is a practical description rather than one single statutory notice. HMRC uses targeted letters to encourage taxpayers to review information where its data suggests that income, gains, relief or another item may need checking.', 'The wording matters. Some letters ask for confirmation even if the return is correct; others invite an amendment or disclosure. A nudge letter should not be described automatically as a Section 9A enquiry, discovery assessment or allegation of fraud.'] },
      { title: 'Why might HMRC have written?', paragraphs: ['HMRC may hold information from employers, banks, property records, digital platforms, overseas authorities or other compliance activity. The data may be incomplete, attributed to the wrong person or reported gross, so it must be reconciled rather than accepted or dismissed without evidence.'], bullets: ['Property ownership or rental information', 'Overseas income or assets', 'Cryptoasset or investment transactions', 'Online-platform receipts', 'Reliefs or expenses HMRC wants checked'] },
      { title: 'Check the requested response carefully', paragraphs: ['Record the date, reference, tax years, issue and deadline. Check whether HMRC asks for a certificate, a written explanation, an amended return or use of a disclosure service. Signing a statement without completing the review can create a misleading record.', 'If the letter names an adviser or agent, verify that the adviser has the complete facts and that the response matches the returns and source evidence.'] },
      { title: 'What if the tax position is wrong?', paragraphs: ['Identify every affected year and source before choosing a correction route. A recent return may still be amendable; older, offshore, property or deliberate issues may require a different disclosure process.', 'Do not disclose only the item HMRC mentioned if the same review identifies a connected omission. Equally, do not concede HMRC’s suggested figure without checking ownership, costs, tax already paid and the correct tax treatment.'] }
    ],
    actions: ['Read the full letter and all enclosures', 'Record the response deadline and tax years', 'Obtain the relevant returns and source records', 'Reconcile HMRC’s apparent information to the declared position', 'Choose the correct response, amendment or disclosure route', 'Keep the final response and proof of submission'],
    records: ['HMRC nudge letter and envelope', 'Filed returns and computations', 'Bank, platform or property statements', 'Contracts and ownership evidence', 'Foreign tax or withholding certificates', 'A written year-by-year reconciliation'],
    example: { title: 'Example: HMRC writes about online-platform income', paragraphs: ['HMRC’s figure represents gross receipts. The seller’s records include refunds, personal-item sales and trading sales, while platform fees were deducted before payment.', 'The taxpayer reconciles gross receipts to taxable trading income, checks whether the filed return is correct and responds with a clear schedule. Any genuine omission is corrected through the appropriate route rather than treating the platform total as taxable profit.'] },
    faqs: [['Is a nudge letter a tax investigation?', 'Not necessarily. Its legal and practical significance depends on the wording and any statutory notice accompanying it.'], ['Do I need to respond if my return is correct?', 'Follow the letter. Some nudge letters specifically ask for confirmation or an explanation even where no correction is needed.'], ['Can a nudge letter affect penalties?', 'The timing of HMRC contact can be relevant to whether a later disclosure is treated as prompted or unprompted.']],
    sources: [['GOV.UK: Tax compliance checks', 'https://www.gov.uk/tax-compliance-checks'], ['GOV.UK: If you have not told HMRC about income', 'https://www.gov.uk/undeclared-income']]
  },
  {
    slug: 'hmrc-asking-for-receipts-expense-evidence',
    category: 'Letters and requests',
    title: 'HMRC Asking for Receipts or Expense Evidence: How to Respond',
    description: 'A practical guide to HMRC receipt and expense requests, missing records, business purpose, reconstructed evidence and preparing an indexed response.',
    directAnswer: 'If HMRC asks for receipts or proof of expenses, map each requested item to the tax return, period and business purpose. Supply organised evidence with a reconciliation rather than an unsorted bundle. Where an original receipt is missing, seek a duplicate or explain a transparent reconstruction; never create or alter a document to make it appear original.',
    enquiryCategory: 'self-assessment-enquiry',
    canonicalGuide: { title: 'HMRC Self Assessment enquiry guide', href: '/knowledge-base/hmrc-self-assessment-enquiry-guide' },
    sections: [
      { title: 'What HMRC may be checking', paragraphs: ['HMRC may test whether an expense was incurred, paid, connected with the business or taxable activity, recorded in the correct period and treated correctly for tax. A bank payment proves money moved but does not always prove the nature or deductibility of the cost.', 'The evidence needed differs for repairs, travel, professional fees, use of home, stock, capital expenditure and mixed private/business costs.'] },
      { title: 'How to organise an evidence response', paragraphs: ['Create a schedule using HMRC’s question numbering. Include the ledger reference, date, supplier, gross amount, tax treatment, document name and short explanation. Reconcile the schedule to the return or accounts before sending it.', 'Use consistent file names and retain originals. Explain samples or agreed limitations clearly rather than allowing HMRC to assume that a partial pack represents the complete population.'] },
      { title: 'What if receipts are missing?', paragraphs: ['Request duplicates from suppliers, banks, card providers or software platforms. Alternative evidence may include contracts, correspondence, delivery records, statements and proof of the underlying transaction.', 'Label any reconstruction and state its methodology. An estimate should be supportable and reproducible; it must not be presented as an original invoice or receipt.'] },
      { title: 'Private use and capital expenditure', paragraphs: ['Where expenditure has mixed use, explain the apportionment and evidence. A cost can be genuine yet not fully deductible. Improvements and assets may require capital treatment rather than being claimed immediately as repairs or ordinary expenses.', 'If the original return used the wrong treatment, calculate the complete correction and consider whether another year or tax is affected.'] }
    ],
    actions: ['List every requested expense and period', 'Reconcile the expense schedule to the filed return', 'Locate originals or request third-party duplicates', 'Explain business purpose and any private-use restriction', 'Separate revenue expenses from capital items', 'Index attachments and retain proof of delivery'],
    records: ['Invoices and receipts', 'Bank and card statements', 'Contracts and supplier correspondence', 'Mileage or travel records', 'Accounting-ledger extracts', 'Apportionment and capital/revenue analysis'],
    example: { title: 'Example: missing repair invoices', paragraphs: ['A landlord claimed several repairs but lost two invoices. Bank statements show payment and the contractor provides duplicate invoices and correspondence describing the work.', 'The landlord separates replacement of worn components from a larger improvement, updates the expense schedule and explains which documents are duplicates. The response does not backdate newly created paperwork.'] },
    faqs: [['Does no receipt automatically mean no deduction?', 'Not automatically, but the taxpayer must still establish the expense and its tax treatment with reliable evidence.'], ['Can HMRC ask for bank statements as well?', 'It may request relevant statements where they help verify payment, income or another tax position.'], ['Should I send every receipt I have?', 'Respond to the defined request with an indexed, reconciled pack rather than an unexplained archive.']],
    sources: [['GOV.UK: Tax compliance checks', 'https://www.gov.uk/tax-compliance-checks'], ['HMRC compliance-check factsheets', 'https://www.gov.uk/government/collections/hm-revenue-and-customs-compliance-checks-factsheets']]
  },
  {
    slug: 'hmrc-asking-for-business-records',
    category: 'Letters and requests',
    title: 'HMRC Asking for Business Records: A Response Checklist',
    description: 'Understand which business records HMRC may request, how to define scope, preserve digital evidence and prepare reconciliations for a compliance check.',
    directAnswer: 'When HMRC asks for business records, first identify the tax, period, legal basis and issue being checked. Preserve accounting data and audit trails, reconcile the requested records to filed returns and provide an indexed response. Do not give unrestricted system access or withhold a formal notice without understanding the applicable powers and deadlines.',
    enquiryCategory: 'compliance-check',
    canonicalGuide: { title: 'HMRC compliance check guide', href: '/knowledge-base/what-is-an-hmrc-compliance-check' },
    sections: [
      { title: 'Which records might be relevant?', paragraphs: ['The request may cover accounts, ledgers, invoices, bank statements, contracts, payroll, VAT records, till data, merchant reports, stock records or computations. Relevance depends on the taxpayer, tax and issue.', 'A formal information notice is not identical to an informal request. Check accompanying factsheets, restrictions and any appeal rights while preserving the compliance deadline.'], bullets: ['Accounting-system exports and audit trails', 'Sales, purchase and bank records', 'VAT and payroll submissions', 'Contracts and transaction documents', 'Management accounts and reconciliations'] },
      { title: 'Preserve digital evidence', paragraphs: ['Export data before software access expires and keep native reports where possible. Record filters, date ranges and report settings so figures can be reproduced.', 'Never edit an original file to remove awkward entries. If a corrected schedule is needed, preserve the original and explain every adjustment.'] },
      { title: 'Reconcile records to returns', paragraphs: ['Connect sales systems and bank receipts to turnover, expenses to ledgers, payroll to RTI submissions and VAT accounts to VAT returns. Explain transfers, loans, timing items and corrected submissions.', 'A well-designed reconciliation can resolve apparent discrepancies before they become broader questions. Unsupported descriptions such as “transfer” or “director loan” should be evidenced.'] },
      { title: 'Visits and system access', paragraphs: ['If HMRC proposes a visit, request an agenda and clarify who, what and which systems are required. Relevant read-only reports or supervised access may be more appropriate than sharing administrator credentials.', 'Private premises, third-party data and material outside the stated scope require careful handling. Keep a detailed meeting note and confirm follow-up actions in writing.'] }
    ],
    actions: ['Identify whether the request is informal or statutory', 'Define the taxes, years and business entities in scope', 'Preserve accounting and operational data', 'Prepare return-to-record reconciliations', 'Index every file and explain unavailable records', 'Agree secure transfer and access arrangements'],
    records: ['Opening letter or information notice', 'Filed returns and accounts', 'General ledger and audit trail', 'Bank and merchant statements', 'Payroll and VAT reports', 'Document index and reconciliation schedules'],
    example: { title: 'Example: restaurant sales records', paragraphs: ['HMRC asks for till reports, card settlements, bankings and VAT returns. The restaurant exports daily till data and reconciles gross sales, discounts, refunds, cash and card receipts to the VAT account.', 'Differences caused by tips and third-party delivery fees are evidenced separately. HMRC receives relevant reports, not an unexplained data dump or unrestricted system login.'] },
    faqs: [['Can HMRC request electronic accounting data?', 'It may request relevant digital records and inspect business records under applicable compliance powers.'], ['What if old software is no longer accessible?', 'Document the loss, contact the provider and reconstruct from reliable exports and third-party records.'], ['Can HMRC visit the business?', 'HMRC may arrange visits and has inspection powers in defined circumstances; check the legal basis and scope.']],
    sources: [['GOV.UK: Tax compliance checks', 'https://www.gov.uk/tax-compliance-checks'], ['HMRC compliance-check factsheets', 'https://www.gov.uk/government/collections/hm-revenue-and-customs-compliance-checks-factsheets']]
  },
  {
    slug: 'hmrc-penalty-notice',
    category: 'Penalties',
    title: 'HMRC Penalty Notice: What to Check Before You Pay or Appeal',
    description: 'Received an HMRC penalty notice? Check the decision, amount, deadline, reasonable-excuse evidence and correct appeal route before responding.',
    directAnswer: 'Read an HMRC penalty notice immediately and identify the tax, failure, period, amount and appeal instructions. Many HMRC appeals use a 30-day period, but the notice and applicable rules control. Paying, appealing and complaining are different actions. Preserve the appeal deadline even if you are still gathering evidence or discussing the matter with HMRC.',
    enquiryCategory: 'penalties-and-tax-appeals',
    canonicalGuide: { title: 'How to appeal an HMRC penalty', href: '/knowledge-base/appeal-hmrc-tax-penalty' },
    sections: [
      { title: 'Identify exactly what HMRC has penalised', paragraphs: ['A notice may concern late filing, late payment, an inaccurate return, failure to notify, an information notice or another obligation. Several penalties can arise from the same event and may require separate grounds.', 'Check the taxpayer, reference, period, statutory basis and calculation. Do not assume that accepting the underlying tax means the penalty must also be correct.'] },
      { title: 'Protect the appeal deadline', paragraphs: ['GOV.UK states that certain tax decisions and penalties can be challenged. Thirty days is common, but use the deadline and method on the notice. Informal telephone calls, complaints and ongoing correspondence do not automatically extend time.', 'Where evidence is still being collected, a concise appeal can identify the decision and grounds and state that supporting material will follow, if the applicable process permits. Keep proof of submission.'] },
      { title: 'Build evidence for the actual ground', paragraphs: ['A reasonable-excuse appeal should show what prevented compliance, when it operated, what alternatives existed and how quickly the failure was remedied. Calculation and behaviour appeals require different evidence.', 'A generic template or hardship statement may not address the statutory test. Put events in date order and connect every document to the obligation missed.'] },
      { title: 'Review, tribunal and payment', paragraphs: ['If HMRC does not agree, a statutory review or First-tier Tribunal route may be available. Each stage can create a new deadline. Alternative dispute resolution does not itself preserve appeal rights.', 'The payment position should be checked separately. Interest or collection may continue depending on the tax and procedure, even while correctness is disputed.'] }
    ],
    actions: ['Save the complete notice and envelope', 'Record the decision and appeal deadline', 'Recalculate the penalty independently', 'Choose the correct statutory ground', 'Prepare a dated evidence chronology', 'Submit through the stated channel and retain proof'],
    records: ['Penalty notice', 'Returns and filing receipts', 'Payment confirmations', 'Medical, system or delivery evidence', 'HMRC correspondence', 'Alternative penalty calculation'],
    example: { title: 'Example: late filing after a system failure', paragraphs: ['A company appeals a late-filing penalty after its filing software failed. It provides status reports, support tickets, attempted submissions and the eventual filing receipt.', 'The appeal explains why the failure prevented compliance and what happened after service was restored. It does not rely only on a screenshot saying the system was unavailable.'] },
    faqs: [['Should I pay before appealing?', 'Payment and postponement rules differ. Follow the notice and obtain advice where collection or interest is material.'], ['What if the 30-day period has passed?', 'Submit the appeal promptly with the underlying grounds and a complete explanation for the delay; late admission is not automatic.'], ['Is a complaint the same as an appeal?', 'No. A complaint usually concerns service, while an appeal challenges the legal decision or amount.']],
    sources: [['GOV.UK: Disagree with a tax decision or penalty', 'https://www.gov.uk/tax-appeals'], ['GOV.UK: Appeal to the tax tribunal', 'https://www.gov.uk/tax-tribunal']]
  },
  {
    slug: 'incorrect-self-assessment-return',
    category: 'Return errors',
    title: 'Incorrect Self Assessment Return: How to Correct a Mistake',
    description: 'Found an error in a Self Assessment return? Check the amendment window, recalculate the complete position, preserve evidence and use the correct HMRC route.',
    directAnswer: 'A Self Assessment return can generally be amended within 12 months of its filing deadline. If that window has passed, the correction route depends on whether tax was underpaid or overpaid and on the affected years. Recalculate the complete return before amending, keep the original and corrected computations, and do not wait for HMRC to identify a known error.',
    enquiryCategory: 'self-assessment-enquiry',
    canonicalGuide: { title: 'HMRC Self Assessment enquiry guide', href: '/knowledge-base/hmrc-self-assessment-enquiry-guide' },
    sections: [
      { title: 'First establish what is wrong', paragraphs: ['Identify the tax year, return entry, cause and whether the error affects income, expenses, gains, reliefs, tax deducted or payments on account. Check connected supplementary pages and later returns using the same treatment.', 'Do not overwrite working papers without preserving the filed version. Create an original-to-corrected bridge showing every change and its tax effect.'] },
      { title: 'Is the return still amendable?', paragraphs: ['GOV.UK states that a return can generally be corrected within 12 months of the Self Assessment deadline. Online and paper amendment methods differ, and commercial software users may need provider support.', 'After the amendment window, underpayments should be reported to HMRC in writing or through an appropriate disclosure route. Overpayment relief has separate requirements and time limits.'] },
      { title: 'Calculate tax, interest and possible penalties', paragraphs: ['An amendment updates the tax bill and may affect payments on account and interest. Penalties depend on the nature of the error, behaviour, timing and disclosure; an error does not automatically mean a penalty.', 'Record when and how the mistake was discovered and the checks taken afterwards. This chronology can matter if HMRC later considers reasonable care or disclosure quality.'] },
      { title: 'What if HMRC has already contacted you?', paragraphs: ['If an enquiry, nudge letter or compliance check is open, do not submit an isolated amendment without coordinating it with the correspondence. HMRC may require the issue to be dealt with inside the open process.', 'A known error elsewhere on the return should not be concealed merely because HMRC asked about another entry. Obtain advice on a complete and consistent correction.'] }
    ],
    actions: ['Download the filed return and computation', 'Identify every affected entry and year', 'Recalculate the complete tax position', 'Check whether the amendment window remains open', 'Use the correct amendment, written claim or disclosure route', 'Save acknowledgements and monitor the revised statement'],
    records: ['Original return and filing receipt', 'Corrected computation', 'Source documents for the change', 'Original-to-corrected reconciliation', 'Discovery chronology', 'HMRC amendment acknowledgement'],
    example: { title: 'Example: omitted freelance income', paragraphs: ['A taxpayer discovers freelance income was omitted from an otherwise complete return. They reconstruct gross receipts and allowable business expenses and check whether the same activity continued into the following year.', 'If the amendment window is open, the complete return is amended and the revised bill checked. If it is closed, the taxpayer uses the appropriate written or disclosure route rather than inserting the income into the wrong year.'] },
    faqs: [['How long do I have to amend a return?', 'GOV.UK states that a correction can generally be made within 12 months of the Self Assessment deadline.'], ['What if I paid too much tax?', 'An amendment may be available within the normal window; after that, overpayment relief has specific conditions and time limits.'], ['Will correcting a return cause an enquiry?', 'HMRC may review an amendment, but correcting a known error accurately is preferable to leaving it unresolved.']],
    sources: [['GOV.UK: Change your Self Assessment return', 'https://www.gov.uk/self-assessment-tax-returns/corrections'], ['GOV.UK: If you have not told HMRC about income', 'https://www.gov.uk/undeclared-income']]
  },
  {
    slug: 'vat-return-error',
    category: 'Return errors',
    title: 'VAT Return Error: How to Correct It and Tell HMRC',
    description: 'Found an error on a submitted VAT Return? Check the current correction method, evidence, time limits, penalties and action during an HMRC check.',
    directAnswer: 'A VAT Return error should be recorded and corrected using the method that applies to its net value and circumstances. HMRC’s current service may direct you to update a later return, correct the error online or notify HMRC in writing. Preserve the error calculation and do not use an old VAT652 process. Deliberate, careless and already-investigated errors need particular care.',
    enquiryCategory: 'vat-paye-enquiry',
    canonicalGuide: { title: 'HMRC VAT compliance check guide', href: '/knowledge-base/hmrc-vat-compliance-check' },
    sections: [
      { title: 'Confirm that it is an error', paragraphs: ['Identify the VAT period, boxes affected, output or input tax, net effect and cause. Normal accounting adjustments—such as properly timed credit notes, partial-exemption adjustments or bad-debt relief—are not necessarily errors.', 'Preserve the original VAT account and create a separate correction record showing discovery date, affected period, documents and calculation.'] },
      { title: 'Choose the current correction method', paragraphs: ['HMRC guidance explains that previous-return errors may be corrected through a later VAT Return, an online correction or written notification, depending on the facts and thresholds. Its online checker uses the net error and sales value.', 'Use the current GOV.UK process. HMRC states that form VAT652 is no longer used. Large errors, deliberate matters and errors outside ordinary conditions should not be pushed into a later return without checking the notification requirement.'] },
      { title: 'Time limits and evidence', paragraphs: ['VAT Notice 700/45 explains a general four-year error-correction limit for specified categories, with exceptions including deliberate errors. Apply the rule to the particular output or input-tax error and accounting period.', 'Keep invoices, VAT account entries, calculations, return acknowledgements and the reason for the original treatment. Where a technical VAT position is uncertain, establish the correct liability before calculating the error.'] },
      { title: 'Penalties and open VAT checks', paragraphs: ['Penalties can depend on whether an inaccuracy was careless or deliberate and on the timing and quality of disclosure. An error made despite reasonable care is treated differently, but failure to correct a discovered error can itself create problems.', 'If HMRC has arranged a VAT inspection or started enquiries, coordinate the correction with the officer. Do not present a prompted correction as though HMRC contact had not occurred.'] }
    ],
    actions: ['Preserve the submitted return and VAT account', 'Calculate the net error by VAT period', 'Identify output tax, input tax and the cause', 'Use HMRC’s current correction checker or applicable notification route', 'Record the discovery and disclosure chronology', 'Confirm the corrected VAT and payment position'],
    records: ['Submitted VAT Return', 'VAT account and ledger', 'Sales and purchase invoices', 'Error calculation by period', 'Correction acknowledgement', 'Evidence of payment or repayment'],
    example: { title: 'Example: duplicated input-tax claim', paragraphs: ['A purchase invoice was posted twice and input VAT was claimed twice. The business identifies the affected return, reverses the duplicate in its records and calculates the net correction.', 'It uses HMRC’s current guidance to determine whether correction on a later return or separate notification is required, retaining the original invoice, duplicate posting trail and correction acknowledgement.'] },
    faqs: [['Can I correct every VAT error on the next return?', 'No. The applicable method depends on the net error, circumstances and current HMRC thresholds and conditions.'], ['Is VAT652 still used?', 'HMRC states that VAT Return errors can no longer be corrected using form VAT652.'], ['What if HMRC has already arranged a VAT visit?', 'Coordinate the correction with the check and obtain advice on disclosure and penalty implications.']],
    sources: [['GOV.UK: Check how to tell HMRC about VAT Return errors', 'https://www.gov.uk/guidance/check-if-you-need-to-report-errors-in-your-vat-return'], ['VAT Notice 700/45: Correcting VAT errors', 'https://www.gov.uk/guidance/how-to-correct-vat-errors-and-make-adjustments-or-claims-vat-notice-70045']]
  },
  {
    slug: 'hmrc-compliance-check-letter',
    category: 'Letters and requests',
    title: 'HMRC Compliance Check Letter: What to Do First',
    description: 'Received an HMRC compliance check letter? Identify its scope, protect the deadline, gather the right records and prepare a controlled first response.',
    directAnswer: 'Read the complete HMRC compliance check letter and record the tax, period, questions, documents and response date. A check does not itself prove that anything is wrong. Reconcile the figures before replying, answer HMRC’s numbered questions and request clarification where the scope or legal basis is unclear.',
    enquiryCategory: 'compliance-check',
    canonicalGuide: { title: 'Complete HMRC compliance check guide', href: '/knowledge-base/what-is-an-hmrc-compliance-check' },
    sections: [
      { title: 'Identify the check and its scope', paragraphs: ['HMRC may check taxes, accounts, calculations, Self Assessment, Company Tax Returns and PAYE records. The opening letter should indicate what it wants to review, but later requests may refine or expand the scope.', 'Create a one-sentence scope summary naming the taxpayer, tax, period and issue. Keep formal information notices separate from informal requests because their consequences and appeal rights can differ.'] },
      { title: 'Protect the first deadline', paragraphs: ['Diary the response date immediately. If records cannot reasonably be assembled, contact the officer before expiry, explain why and request a realistic extension. Keep written confirmation of any agreement.', 'An extension is not a reason to postpone preservation. Download records, secure software access and notify the adviser who prepared the return.'] },
      { title: 'Reconcile before explaining', paragraphs: ['Trace each questioned figure to accounts, returns and source documents. Explain timing, classification, ownership and unusual movements with evidence rather than speculation about why HMRC selected the case.', 'If the review discovers a genuine error, establish its complete tax and period effect before deciding how to disclose or correct it.'] },
      { title: 'Prepare a controlled response', paragraphs: ['Use HMRC’s numbering, provide a short explanation before attachments and maintain a document index. Keep facts, estimates and professional conclusions distinct.', 'Do not send an unfiltered archive or answer from memory. If a fact is not yet known, explain how and when it will be verified.'] }
    ],
    actions: ['Record the deadline, tax and period', 'Confirm whether any request is statutory', 'Download the filed return and computation', 'Build a question-and-document response matrix', 'Reconcile every questioned figure', 'Keep the final submission and proof of delivery'],
    records: ['Opening letter and factsheets', 'Filed returns and accounts', 'Tax computations and working papers', 'Bank and transaction records', 'Prior HMRC correspondence', 'Response matrix and document index'],
    example: { title: 'Example: turnover compliance check', paragraphs: ['HMRC asks why company turnover differs from merchant-processor data. The business reconciles gross processor receipts to refunds, VAT, fees and accounting cut-off.', 'The response provides the bridge and source reports. It identifies a small genuine timing error separately instead of claiming that every difference is explained by fees.'] },
    faqs: [['Does a compliance check mean HMRC suspects fraud?', 'No. The letter begins a review, but its seriousness depends on the process, scope and facts.'], ['Can HMRC expand the check?', 'It may ask further questions where information raises additional issues; record and clarify any expansion.'], ['Can an accountant respond?', 'An authorised agent can correspond, but the taxpayer should verify the factual explanation.']],
    sources: [['GOV.UK: Tax compliance checks', 'https://www.gov.uk/tax-compliance-checks'], ['HMRC compliance-check factsheets', 'https://www.gov.uk/government/collections/hm-revenue-and-customs-compliance-checks-factsheets']]
  },
  {
    slug: 'hmrc-asking-for-bank-statements',
    category: 'Letters and requests',
    title: 'HMRC Asking for Bank Statements: What Should You Provide?',
    description: 'Understand why HMRC may request business or personal bank statements, how to assess relevance and how to prepare a bank-to-return reconciliation.',
    directAnswer: 'HMRC may ask for bank statements where they are reasonably required to check income, expenses, transfers, loans or another tax position. Do not send statements without first understanding the accounts and periods requested. Prepare a reconciliation explaining business receipts, transfers and non-trading credits, and obtain advice before refusing, redacting or answering a formal information notice.',
    enquiryCategory: 'compliance-check',
    canonicalGuide: { title: 'Can HMRC ask for bank statements?', href: '/knowledge-base/can-hmrc-ask-for-bank-statements' },
    sections: [
      { title: 'Why HMRC may request statements', paragraphs: ['Statements can help HMRC test whether declared turnover is complete, expenses were paid, loans are genuine and capital introduced or drawings reconcile. A credit does not automatically equal taxable income, but its nature needs evidence.', 'HMRC’s current internal guidance says private accounts should not be requested as a matter of course, although they may be relevant where business records are not robust or transactions cross between business and personal accounts.'] },
      { title: 'Business versus personal accounts', paragraphs: ['Identify every account used for business activity, including savings, merchant and payment-platform balances. For a company, director accounts may become relevant where company receipts or expenses moved through them.', 'Joint accounts and wholly private transactions require careful handling. Ask HMRC to explain relevance and period; do not redact material unilaterally where context could be lost.'] },
      { title: 'Prepare a bank reconciliation', paragraphs: ['Classify sales, refunds, loans, owner funding, tax repayments, transfers and reversals. Tie net trading receipts to the ledger, accounts and relevant return.', 'Unsupported labels invite more questions. Evidence larger or unusual credits with contracts, loan documents, transfer trails or asset-sale records.'] },
      { title: 'Responding safely', paragraphs: ['Confirm the secure delivery method and preserve original statements. Name files consistently and provide a schedule so the officer can follow the explanation.', 'If a formal Schedule 36 notice is broad, difficult or contains protected material, protect its deadline and obtain advice on compliance and any appeal right.'] }
    ],
    actions: ['List all accounts used in the relevant period', 'Confirm why each requested account is relevant', 'Export complete unaltered statements', 'Reconcile credits to turnover and non-trading sources', 'Agree handling of unrelated private data', 'Submit an indexed pack securely'],
    records: ['Business and relevant personal statements', 'Cashbook and general ledger', 'Merchant-processor reports', 'Loan and capital evidence', 'Director loan or drawings accounts', 'Bank-to-return reconciliation'],
    example: { title: 'Example: personal account used temporarily', paragraphs: ['A sole trader received customer payments into a personal account while changing banks. The trader identifies the affected months and reconciles customer receipts to invoices and declared turnover.', 'The response explains the temporary arrangement and deals with unrelated private transactions under an agreed scope rather than denying that the account is relevant.'] },
    faqs: [['Can HMRC ask for personal bank statements?', 'It may where they are relevant to establishing the correct tax position; private accounts should not be requested automatically.'], ['Does every bank credit count as income?', 'No. Transfers, loans and other receipts may not be taxable, but they should be evidenced.'], ['Can I redact private transactions?', 'Do not redact unilaterally. Clarify scope or obtain advice, particularly where a formal notice applies.']],
    sources: [['HMRC manual: private bank accounts', 'https://www.gov.uk/hmrc-internal-manuals/compliance-handbook/ch207320'], ['GOV.UK: Tax compliance checks', 'https://www.gov.uk/tax-compliance-checks']]
  },
  {
    slug: 'hmrc-vat-inspection',
    category: 'Letters and requests',
    title: 'HMRC VAT Inspection: What to Expect and How to Prepare',
    description: 'Prepare for an HMRC VAT visit or inspection with a clear agenda, VAT-account reconciliation, evidence checklist and controlled system access.',
    directAnswer: 'HMRC may inspect VAT records to check that the correct amount has been paid or reclaimed. It usually contacts the business to arrange the visit and confirm the records required, although unannounced contact is possible. Reconcile VAT returns to the VAT account, ledgers and source documents before the inspection and clarify the scope and access arrangements.',
    enquiryCategory: 'vat-paye-enquiry',
    canonicalGuide: { title: 'Complete HMRC VAT compliance check guide', href: '/knowledge-base/hmrc-vat-compliance-check' },
    sections: [
      { title: 'Before the VAT inspection', paragraphs: ['GOV.UK says HMRC normally gives notice and confirms what it wants to see, how long the visit may take and whether premises will be inspected. Ask for the agenda, VAT periods, attendees and proposed system access.', 'Verify that the contact is genuine using official channels if necessary. Notify the accountant or adviser and identify staff who understand the sales, purchasing and VAT processes.'] },
      { title: 'Reconcile the VAT returns', paragraphs: ['Tie each return to the VAT account, sales and purchase ledgers, control accounts and submitted figures. Explain credit notes, timing, imports, exports, reverse charge and scheme adjustments.', 'Select unusual or high-value transactions for deeper evidence review. Confirm VAT rates, tax points, business purpose and input-tax documentation.'] },
      { title: 'Manage the visit and systems', paragraphs: ['Provide relevant reports or supervised read-only access rather than administrator credentials. Staff should answer within their knowledge and offer to verify uncertain facts.', 'Keep a contemporaneous note of questions, documents viewed, samples selected and follow-up actions. Correct material misunderstandings promptly in writing.'] },
      { title: 'After the inspection', paragraphs: ['HMRC should write with findings, corrections, record-keeping requirements and any penalty. Recalculate proposed adjustments and distinguish tax from penalty behaviour.', 'A decision may have a short appeal deadline. Continued discussion does not automatically extend it, so diary the applicable date immediately.'] }
    ],
    actions: ['Confirm the visit is genuine', 'Request the scope, agenda and record list', 'Reconcile VAT returns to accounts', 'Review high-risk transactions and evidence', 'Plan supervised system access', 'Record the visit and protect follow-up deadlines'],
    records: ['VAT inspection letter', 'VAT returns and VAT account', 'Sales and purchase ledgers', 'Invoices and import/export evidence', 'Partial exemption or scheme calculations', 'Meeting note and adjustment schedule'],
    example: { title: 'Example: repayment VAT inspection', paragraphs: ['A business claimed a substantial repayment after equipment purchases. It prepares invoices, payment records, business-use evidence and a fixed-asset reconciliation.', 'The officer receives a clear explanation of the exceptional claim and any private-use restriction, not merely a folder of invoices.'] },
    faqs: [['How much notice will HMRC give?', 'GOV.UK says VAT visits are normally arranged and commonly involve notice, but HMRC can also contact or visit without an appointment.'], ['Can I ask to delay a visit?', 'GOV.UK says a business can ask HMRC to delay an arranged VAT visit. Agreement is not automatic.'], ['Can I appeal the outcome?', 'Certain HMRC VAT decisions can be appealed; follow the decision notice and deadline.']],
    sources: [['GOV.UK: VAT visits and inspections', 'https://www.gov.uk/vat-visits-inspections'], ['GOV.UK: VAT record keeping', 'https://www.gov.uk/vat-record-keeping']]
  },
  {
    slug: 'hmrc-paye-compliance-check',
    category: 'Letters and requests',
    title: 'HMRC PAYE Compliance Check: Employer Preparation Steps',
    description: 'Received a PAYE compliance check letter? Reconcile payroll, RTI, benefits, expenses and worker status before responding to HMRC.',
    directAnswer: 'A PAYE compliance check can examine employee pay, deductions, RTI submissions, payments to HMRC, expenses, benefits and worker status. Identify the years and issues, reconcile payroll reports to accounts and HMRC submissions, and prepare worker-specific evidence where employment status or off-payroll treatment is questioned.',
    enquiryCategory: 'vat-paye-enquiry',
    canonicalGuide: { title: 'Complete PAYE employer compliance guide', href: '/knowledge-base/hmrc-paye-employer-compliance-check' },
    sections: [
      { title: 'What HMRC may check', paragraphs: ['HMRC can review PAYE records and returns. The letter may focus on payroll calculations, National Insurance, benefits, expenses, termination payments, directors, employment status, off-payroll working or CIS interactions.', 'Define the precise scope before producing records. A combined employer-compliance check can span more than payroll software alone.'] },
      { title: 'Build a payroll reconciliation', paragraphs: ['Tie gross pay, tax, employee and employer National Insurance, statutory payments and net pay to Full Payment Submissions, Employer Payment Summaries, the general ledger and payments to HMRC.', 'List original and corrected submissions. Explain timing, leavers, starters and payroll adjustments rather than forcing the accounts to match an incorrect report.'] },
      { title: 'Benefits, expenses and directors', paragraphs: ['Reconcile P11Ds, payrolled benefits, PAYE Settlement Agreements, company cards, expense claims and director loan accounts. Separate qualifying business reimbursements from taxable benefits.', 'Mixed private use, employee contributions and exemptions need evidence. The accounting entry alone does not settle the PAYE treatment.'] },
      { title: 'Worker status questions', paragraphs: ['Employment status depends on the full facts, not the contract label or CIS registration alone. Prepare evidence about personal service, control, substitution, financial risk, equipment and actual working practices.', 'Review workers individually or in genuinely comparable groups and avoid retrospective contracts that do not reflect reality.'] }
    ],
    actions: ['Identify taxes, years and workforce groups', 'Reconcile payroll to RTI and accounts', 'Review benefits, expenses and director transactions', 'Check payments and arrears to HMRC', 'Prepare worker-status evidence where relevant', 'Submit indexed records with explanations'],
    records: ['Payroll reports and RTI receipts', 'PAYE payment records', 'P11Ds and benefit calculations', 'Expense and company-card records', 'Employment and contractor agreements', 'Accounts-to-payroll reconciliation'],
    example: { title: 'Example: staff cost differs from payroll', paragraphs: ['The accounts show higher staff costs because they include employer pension contributions and agency workers outside the main payroll report.', 'The employer prepares a bridge by category and investigates payments to agency workers separately. It does not treat the ledger difference as proof that all payments were correctly outside PAYE.'] },
    faqs: [['How long must PAYE records be kept?', 'GOV.UK states that specified PAYE records generally need to be kept for three years from the end of the tax year they relate to.'], ['Can HMRC check contractor status?', 'Yes. Employer compliance can include whether workers should have been treated as employees.'], ['Can an adviser attend a meeting?', 'A properly authorised adviser can assist with an employer compliance check.']],
    sources: [['GOV.UK: PAYE record keeping', 'https://www.gov.uk/paye-for-employers/keeping-records'], ['GOV.UK: Tax compliance checks', 'https://www.gov.uk/tax-compliance-checks']]
  },
  {
    slug: 'forgot-to-declare-income',
    category: 'Return errors',
    title: 'Forgot to Declare Income to HMRC: What to Do Now',
    description: 'Forgot to report taxable income? Identify every source and year, calculate the tax and choose the correct amendment or disclosure route.',
    directAnswer: 'Tell HMRC about taxable income that was not declared rather than waiting for a data match or enquiry. First establish every affected source and tax year, calculate gross income, allowable costs and tax already paid, then choose the correct return amendment, disclosure facility or open-enquiry response.',
    enquiryCategory: 'undeclared-income-disclosure',
    canonicalGuide: { title: 'Undeclared income and HMRC disclosure help', href: '/hmrc-enquiry-help/undeclared-income-disclosure' },
    sections: [
      { title: 'Identify the complete omission', paragraphs: ['List income by source, ownership and tax year. Common areas include self-employment, rent, foreign income, investments, cryptoassets, platform sales and capital gains.', 'A bank receipt is not always taxable profit. Establish gross income, allowable expenses, acquisition costs, foreign tax and the correct tax regime.'] },
      { title: 'Choose the correct correction route', paragraphs: ['A recent Self Assessment return may still be within its amendment window. Older years, people not registered for Self Assessment, offshore matters and particular campaigns can require other routes.', 'If HMRC has already contacted you, the disclosure may need to be coordinated with the enquiry or letter. Do not describe it as unprompted without checking the chronology.'] },
      { title: 'Calculate tax, interest and penalties', paragraphs: ['Prepare a year-by-year computation and consider tax already deducted, losses and reliefs. Interest generally follows the underlying late tax position.', 'Penalty treatment can depend on behaviour, whether disclosure was prompted and its quality. Record when the omission was discovered and the help and access provided.'] },
      { title: 'Correct future and connected returns', paragraphs: ['Check whether the same income source continues into later years and whether registration or reporting obligations remain. A disclosure should not leave the current year wrong.', 'Keep acknowledgements, payment references and the final disclosure pack. Do not send sensitive documents through the initial website form.'] }
    ],
    actions: ['Inventory income sources and affected years', 'Obtain third-party statements', 'Calculate gross income, costs and tax paid', 'Check amendment and disclosure routes', 'Notify and disclose within applicable deadlines', 'Correct later returns and preserve evidence'],
    records: ['Filed returns', 'Bank and platform statements', 'Invoices and expense records', 'Property or investment documents', 'Foreign tax certificates', 'Tax-and-year disclosure schedule'],
    example: { title: 'Example: undeclared side-hustle income', paragraphs: ['An employee earned money through freelance work and assumed tax was covered by PAYE. They reconstruct invoices and platform receipts and calculate allowable business expenses.', 'The taxpayer checks which return can be amended and how older income must be disclosed, then corrects ongoing reporting rather than putting all receipts into the current year.'] },
    faqs: [['Should I wait for HMRC to contact me?', 'GOV.UK says to tell HMRC as soon as possible about taxable income that has not been declared.'], ['Is all online-platform income taxable?', 'Not necessarily. The activity, ownership, proceeds, costs and applicable allowances must be established.'], ['What if I cannot pay immediately?', 'Do not hide the liability. Calculate and disclose accurately and discuss payment arrangements through the applicable HMRC route.']],
    sources: [['GOV.UK: If you have not told HMRC about income', 'https://www.gov.uk/undeclared-income'], ['GOV.UK: Change your Self Assessment return', 'https://www.gov.uk/self-assessment-tax-returns/corrections']]
  },
  {
    slug: 'undeclared-rental-income',
    category: 'Return errors',
    title: 'Undeclared Rental Income: How to Tell HMRC',
    description: 'A landlord guide to reconstructing rent and expenses, checking Let Property Campaign eligibility and disclosing unpaid tax to HMRC.',
    directAnswer: 'If rental income was not declared, reconstruct the gross rent, ownership, allowable expenses and tax position for every affected year. The Let Property Campaign may be available to eligible individual residential landlords. Notify HMRC through the appropriate route, then meet the disclosure and payment deadline stated in the acknowledgement.',
    enquiryCategory: 'undeclared-income-disclosure',
    canonicalGuide: { title: 'HMRC property income enquiry guide', href: '/knowledge-base/hmrc-property-income-enquiry' },
    sections: [
      { title: 'Check whether the campaign applies', paragraphs: ['HMRC’s Let Property Campaign is aimed at eligible individual landlords with undisclosed tax from residential property, including certain UK and overseas lettings. Companies, trusts and non-residential property may require another route.', 'Use current HMRC eligibility guidance. A recent outstanding return may need filing rather than inclusion in the campaign disclosure.'] },
      { title: 'Reconstruct rent and ownership', paragraphs: ['Prepare rent by property, owner and tax year using tenancy agreements, agent statements, bank deposits and platform reports. Joint owners generally need their own calculations and disclosures.', 'Do not report only cash transferred to a personal account. Establish gross rent and the applicable ownership position.'] },
      { title: 'Review expenses and finance costs', paragraphs: ['Separate day-to-day allowable expenses from capital improvements and private costs. Mortgage payments are not the same as allowable finance costs, and residential finance-cost rules vary by period.', 'Where records are incomplete, HMRC’s campaign guidance permits best estimates, but the basis and evidence should be documented.'] },
      { title: 'Notification, disclosure and payment', paragraphs: ['HMRC’s current guidance says the formal disclosure is due within the period stated after notification acknowledgement; the 2026 campaign guide describes a 90-day period. Start gathering evidence before notifying.', 'The disclosure should calculate tax, interest and penalties and include a payment or agreed arrangement by the stated deadline. Future returns must then remain correct.'] }
    ],
    actions: ['List every property, owner and letting period', 'Check campaign eligibility', 'Reconstruct gross rent by tax year', 'Review expenses, finance costs and losses', 'Notify HMRC and diary the acknowledgement deadline', 'Submit the complete disclosure and payment'],
    records: ['Tenancy agreements', 'Agent and platform statements', 'Bank deposits', 'Mortgage interest certificates', 'Repair and management invoices', 'Ownership and annual profit schedules'],
    example: { title: 'Example: inherited jointly owned property', paragraphs: ['Two siblings inherited and let a residential property but did not declare the rent. They establish ownership dates and shares, then reconstruct rent and expenses from agent statements.', 'Each sibling prepares the appropriate disclosure for their share. Capital refurbishment is separated from ordinary repairs, and future Self Assessment reporting is put in place.'] },
    faqs: [['Who can use the Let Property Campaign?', 'Current HMRC guidance covers eligible individual landlords of residential property; exclusions include companies, trusts and non-residential property.'], ['How long is allowed after notification?', 'HMRC’s 2026 campaign guide states that disclosure and payment must be made within 90 days of the notification acknowledgement. Follow the actual acknowledgement.'], ['What if rental records are missing?', 'Use reliable replacements and documented best estimates rather than invented or backdated records.']],
    sources: [['GOV.UK: Let Property Campaign guide', 'https://www.gov.uk/government/publications/let-property-campaign-your-guide-to-making-a-disclosure/let-property-campaign-your-guide-to-making-a-disclosure'], ['GOV.UK: Paying tax on rental income', 'https://www.gov.uk/renting-out-a-property/paying-tax']]
  }
];

export const problems:ProblemPage[]=[...initialProblems,...phase4Problems];
