import { extraGuides } from './extra-guides';
import { latestGuides } from './latest-guides';
import { expandGuide } from './expand-guide';

export type Guide = { slug:string; category:'Individual'|'Business'|'General'; title:string; shortTitle:string; description:string; keyword:string; secondaryKeywords?:string[]; searchIntent?:string; reviewed?:string; readingTime:string; updated:string; intro:string[]; sections:{title:string; paragraphs:string[]; bullets?:string[]}[]; faqs:[string,string][]; sources:[string,string][] };

const coreGuides: Guide[] = [
  {
    slug:'what-is-an-hmrc-compliance-check', category:'Business', shortTitle:'HMRC compliance checks', keyword:'HMRC compliance check', secondaryKeywords:['HMRC compliance check letter','HMRC tax compliance check','what happens during an HMRC compliance check'], searchIntent:'Understand an HMRC compliance check letter, its scope and the practical steps for responding.', reviewed:'23 July 2026', readingTime:'14 min read', updated:'23 July 2026',
    title:'What Is an HMRC Compliance Check? A Complete UK Guide',
    description:'Received an HMRC compliance check letter? Learn what HMRC can check, what information it may request, your rights, likely timescales and how to respond.',
    intro:[
      'An HMRC compliance check is a review of a person’s or business’s tax position. HM Revenue and Customs may check a tax return, accounts, calculations, payroll records or another part of the tax affairs it administers. The purpose is to establish whether the right amount of tax has been declared and paid.',
      'Receiving an HMRC compliance check letter does not automatically mean HMRC believes you have deliberately done something wrong. Checks can be risk-based, triggered by information that does not match a return, connected to a sector campaign or selected for another compliance reason. What matters is how you interpret the scope, preserve evidence and respond.',
      'This guide explains the process in practical terms for UK taxpayers and businesses. It is general information, not advice on a particular enquiry. Deadlines, powers and strategy depend on the tax, period and exact wording of the notice.'
    ],
    sections:[
      {title:'What can HMRC check?',paragraphs:['HMRC says a compliance check can cover any taxes you pay, accounts and tax calculations, Self Assessment returns, Company Tax Returns, VAT and PAYE records. A check may focus on one entry or expand if the information received raises further questions.','The opening letter should identify the tax, accounting period and issue being considered. Read it carefully. A request that appears routine can still call for records that are commercially sensitive or difficult to reconstruct.'],bullets:['Income Tax and Self Assessment','Corporation Tax and company accounts','VAT returns, invoices and digital records','PAYE, benefits, expenses and employment status','Capital Gains Tax and property transactions','Construction Industry Scheme records']},
      {title:'Why does HMRC open compliance checks?',paragraphs:['HMRC does not normally disclose its risk criteria. Common practical triggers include figures that differ from third-party data, unusual movements between years, recurring repayment claims, sector risks, late returns and information received from another enquiry. None of these, by itself, proves an error.','Avoid guessing why you were selected in correspondence. Start with the notice and the records. A disciplined response answers the actual question, explains genuine anomalies and avoids creating confusion through speculation.']},
      {title:'What happens after an HMRC compliance check letter?',paragraphs:['The caseworker normally asks for information or an explanation and gives a response date. HMRC may then ask follow-up questions, propose a visit, discuss adjustments or decide that no change is needed. More complex checks can involve several rounds of correspondence.','Create a chronology immediately: date received, deadline, tax and period, questions asked, documents requested and any earlier conversations. If the deadline is unrealistic, contact the officer before it expires and explain what is needed. An extension is not automatic, so record any agreement in writing.'],bullets:['Check the reference, tax and period','Tell your accountant or tax adviser promptly','Preserve original records and correspondence','Prepare a document index before sending files','Keep copies of everything supplied','Record calls, dates, names and agreed actions']},
      {title:'HMRC information requests and information notices',paragraphs:['An informal request is not identical to a formal information notice. HMRC has statutory powers to require information and documents that are reasonably required to check a tax position, subject to restrictions and appeal rights in some circumstances. The legal position can be nuanced.','Do not ignore a formal notice. At the same time, do not assume every broad request must be answered exactly as drafted. A specialist can identify what is relevant, whether documents exist, whether they are privileged or otherwise protected, and whether clarification is appropriate.']},
      {title:'Your rights during a tax compliance check',paragraphs:['You may appoint a tax agent and can usually have an adviser present at a meeting or visit. HMRC’s own compliance materials explain rights and obligations, including the right to appeal certain decisions and information notices. HMRC should also tell you when a check starts and explain the outcome.','Cooperation is important, but cooperation does not mean surrendering accuracy or context. If a document could be misunderstood, explain it. If a question assumes something incorrect, correct the premise politely. If you do not know an answer, say what steps you will take to establish it rather than guessing.']},
      {title:'How long does an HMRC compliance check take?',paragraphs:['There is no single HMRC compliance check time limit for completion. A narrow check with accessible records may conclude in weeks or a few months. A business enquiry involving multiple taxes, valuations, overseas matters or disputed behaviour can take much longer.','You can help avoid preventable delay by sending organised responses, answering every numbered question, identifying unavailable records and asking HMRC to confirm which points remain open. Long silence does not necessarily mean the check has ended. Seek written confirmation or a closure notice where the relevant regime provides for one.']},
      {title:'What are the possible outcomes?',paragraphs:['HMRC may close the check with no change, agree an adjustment, make an assessment or amendment, and consider interest and penalties. The penalty position often depends on the underlying behaviour—such as reasonable care, carelessness or deliberate conduct—and on the quality and timing of disclosure.','Do not accept a calculation merely to end the process without checking the tax basis, periods, interest and penalty assumptions. Equally, a well-supported correction made early can reduce uncertainty and may affect penalty mitigation.'],bullets:['No additional tax due','Tax repayment or return adjustment','Additional tax and late-payment interest','Penalty assessment','Appeal, review or dispute resolution']},
      {title:'How to respond: a practical checklist',paragraphs:['A strong response is complete, proportionate and easy to audit. Use the officer’s numbering, provide a short explanation before supporting schedules, name attachments consistently and distinguish facts from estimates.','Before sending, check whether the response answers the requested period only, whether totals reconcile to the return and whether personal data about employees or customers needs secure handling. Never alter an original document. Explain corrections transparently.'],bullets:['Confirm the statutory deadline','Define the scope in one sentence','Reconcile figures to the filed return','Explain gaps or estimates','Use encrypted or approved transfer methods','Ask HMRC to confirm safe receipt']},
      {title:'Preparing records when information is missing',paragraphs:['Missing records do not make the enquiry disappear, but a careful reconstruction is better than an unsupported estimate. Start by identifying what should exist, what has been lost and why. Request replacement statements, invoices or reports from banks, suppliers, payroll providers and software platforms. Export digital records before access expires. Document every reconstruction step so another person can reproduce the calculation.','Separate known figures from estimated figures. Explain the basis of each estimate, the evidence used and any limitations. HMRC may propose its own assumptions where records are inadequate; contemporaneous third-party evidence can help challenge an unreasonable estimate. Never manufacture, backdate or edit evidence to make it look original. If loss resulted from a genuine event such as a system failure, retain proof of that event and the recovery steps taken.']},
      {title:'Compliance check meetings and visits',paragraphs:['HMRC may suggest a telephone call, video meeting or visit. Ask for a written agenda, the names and roles of attendees, the taxes and periods to be discussed, and any documents expected. Decide who will answer technical, accounting and operational questions. A meeting should advance identified issues rather than become an unstructured tour through the business.','During a meeting, listen carefully and answer accurately. Do not guess at dates, processes or figures. Offer to verify matters against records. Keep a contemporaneous note of questions, answers and actions, then confirm important points in writing. If HMRC requests access to premises or systems, understand whether the visit is by agreement or under a statutory inspection power and obtain advice on the scope before it occurs.']},
      {title:'How penalties are considered during a check',paragraphs:['Additional tax and penalties are separate calculations. Where a return contains an inaccuracy, HMRC considers the behaviour that led to it, whether it was prompted or unprompted disclosure, and the quality of disclosure. “Quality” commonly concerns how much help was given, how promptly the issue was disclosed and whether HMRC received access to relevant records. The exact statutory regime depends on the failure.','A penalty discussion should identify each alleged inaccuracy, the behaviour HMRC attributes to it and the evidence supporting that conclusion. Reasonable care depends on the taxpayer’s circumstances and the complexity of the issue. Using an adviser is relevant but not a complete answer. Show the systems, checks, questions and review undertaken when the return was prepared, and distinguish an innocent technical disagreement from careless or deliberate conduct.']},
      {title:'Managing communication with the HMRC caseworker',paragraphs:['Good case management is consistent, courteous and written wherever possible. Nominate one person to coordinate replies so HMRC does not receive conflicting explanations from directors, employees and advisers. Acknowledge letters promptly, provide a realistic date for a full response and identify urgent issues separately. If a telephone discussion changes the scope or deadline, confirm your understanding by email or letter. A clear audit trail protects both sides from later disagreement.','Ask the officer to identify which questions remain unresolved after each substantial response. Where HMRC repeats a request, refer to the earlier answer and attachment rather than sending a new version that may create inconsistencies. If progress stalls, propose a short agenda-led call. Escalation or a complaint may be appropriate for unreasonable service issues, but it should not replace cooperation with valid information requests or the separate appeal process for substantive tax decisions.']},
      {title:'When should you get specialist help?',paragraphs:['Consider specialist HMRC enquiry help if the request is broad, records are incomplete, undeclared income may exist, HMRC alleges careless or deliberate behaviour, a meeting is proposed, or the tax at stake is material. Specialist support is also useful when your regular accountant prepared the figures now being challenged.','Early advice can be more valuable than late damage control. An adviser can assess exposure, separate factual from legal questions, manage correspondence and plan a disclosure without overstating or concealing the position.']},
      {title:'Key takeaway',paragraphs:['Treat a compliance check as a managed evidence exercise. Read the letter, protect the deadline, understand the scope and respond accurately. Do not panic, ignore it or send a disorganised archive. The objective is a clear, supportable resolution.']}
    ],
    faqs:[['Is an HMRC compliance check the same as an investigation?','HMRC commonly uses “compliance check” for a range of checks and enquiries. The seriousness and legal framework depend on the tax and notice, so the wording should be reviewed in context.'],['Can HMRC check my bank account?','HMRC may request relevant financial information and has statutory information powers. The route and safeguards depend on the circumstances. Get advice if a request appears unusually broad.'],['Can I refuse an HMRC visit?','Some visits are by agreement, while HMRC has inspection powers in defined circumstances. Check the notice and obtain advice before refusing or agreeing to a visit.'],['Will I receive a penalty?','Not automatically. Penalties depend on whether tax is wrong, the reason for the inaccuracy or failure, and other statutory factors. A check can close with no adjustment.']],
    sources:[['GOV.UK: Tax compliance checks','https://www.gov.uk/tax-compliance-checks'],['HMRC compliance checks factsheets','https://www.gov.uk/government/collections/hm-revenue-and-customs-compliance-checks-factsheets']]
  },
  {
    slug:'hmrc-self-assessment-enquiry-guide', category:'Individual', shortTitle:'Self Assessment enquiries', keyword:'HMRC Self Assessment enquiry', secondaryKeywords:['HMRC Self Assessment enquiry letter','Section 9A enquiry','HMRC tax return investigation'], searchIntent:'Understand and respond to an HMRC Self Assessment enquiry notice or information request.', reviewed:'23 July 2026', readingTime:'15 min read', updated:'23 July 2026',
    title:'HMRC Self Assessment Enquiry: What to Do After a Letter',
    description:'A practical guide to HMRC Self Assessment enquiry letters, enquiry windows, requested records, closure notices, amendments, penalties and your next steps.',
    intro:['An HMRC Self Assessment enquiry is a formal check into a tax return. HMRC does not need to show that the return is wrong before opening an enquiry within the statutory window; it must give written notice. The enquiry may concern one figure or the whole return.','The first days matter. Find the response deadline, identify the return and tax year, and preserve the records used to prepare it. Do not assume that a request for information is either harmless or hostile. The right response is factual, organised and proportionate.','This UK guide explains enquiry notices, time limits and practical steps. Tax law changes and exceptions apply, particularly where HMRC considers a discovery assessment after the ordinary enquiry window. Obtain advice on your own facts.'],
    sections:[
      {title:'What is a Section 9A enquiry?',paragraphs:['For individual Self Assessment returns, HMRC’s main formal enquiry power is commonly called a Section 9A enquiry, referring to the Taxes Management Act 1970. HMRC gives notice that it intends to enquire into the return. The notice should identify the relevant return.','An enquiry does not prove an inaccuracy. HMRC’s internal manual states that an officer may enquire into any return if the legal conditions are met. Only one notice may generally be issued for a particular return or amendment, although the scope of that enquiry can be significant.']},
      {title:'The Self Assessment enquiry window',paragraphs:['A common low-hanging search question is: how long does HMRC have to open a Self Assessment enquiry? For an on-time return, the ordinary window is generally up to 12 months after the return was delivered. Different calculation rules can apply to late returns and amendments.','Do not calculate the deadline from memory. Check the filing date, actual delivery date, amendment history and the date notice was given. Even after the ordinary window, HMRC may consider discovery assessment powers if statutory conditions are met, with time limits depending on the circumstances.']},
      {title:'Full and aspect enquiries',paragraphs:['People often refer to “aspect” and “full” enquiries. An aspect enquiry focuses on one or more specific entries; a full enquiry is broader. These labels are useful descriptions, but the actual scope comes from the legislation, notice and correspondence.','If HMRC begins with rental expenses, answer that issue carefully. Avoid volunteering unrelated material without understanding why it is relevant. However, never conceal a known error elsewhere. A separate disclosure strategy may be required.']},
      {title:'What records can HMRC request?',paragraphs:['Requests may include bank statements, invoices, receipts, tenancy records, mileage logs, dividend vouchers, employment documents, capital gains computations and explanations of private expenditure. Information should be reasonably required to check the tax position.','Reconstructing records is sometimes possible when originals are missing, but label estimates and explain the method. Do not create backdated documents. A transparent schedule supported by third-party evidence is stronger than an unexplained number.'],bullets:['The filed return and tax computation','Working papers used by you or your accountant','Source documents for income and expenses','Contracts, statements and transaction records','A written explanation of unusual entries','Reconciliations between accounts and returns']},
      {title:'How to answer the opening letter',paragraphs:['Read each question twice and prepare a response matrix. Note the information requested, the period, who holds it and whether it exists. Address every numbered point. If a question is ambiguous, seek clarification rather than answer a broader question you think HMRC intended.','Lead with a concise covering letter. Attach an indexed evidence pack. Reconcile schedules to the return and explain differences. Keep proof of delivery and a final copy. If an accountant responds, review the letter yourself because you remain responsible for ensuring the facts are accurate.']},
      {title:'Common enquiry areas for individuals',paragraphs:['HMRC enquiries frequently examine property income, self-employment expenses, employment status, dividends, capital gains, foreign income and the source of funds. Each area has its own evidence and tax rules.','For example, an HMRC rental income enquiry may compare declared rent with property ownership and third-party data. The response should distinguish gross rent, allowable expenses, capital costs, private use and jointly owned interests. Generic statements rarely resolve a figures-based query.'],bullets:['Rental income and property expenses','Self-employed turnover and business expenses','Capital gains on property, shares or cryptoassets','Foreign income and offshore assets','Employment expenses and benefits','Pension contributions and relief claims']},
      {title:'Meetings and interviews with HMRC',paragraphs:['A meeting can help resolve factual issues, but it should have an agenda and a purpose. Ask who will attend, what topics will be covered and whether documents are required. You can usually have an adviser with you.','Prepare a timeline and rehearse accurate explanations without scripting false certainty. Answer the question asked. If you do not remember, say so and offer to check records. After the meeting, create a note and correct material misunderstandings promptly.']},
      {title:'Property income enquiries',paragraphs:['An HMRC property income enquiry may examine ownership, gross rent, agent statements, mortgage interest, repairs, improvements and periods of private occupation. Reconcile rent received to bank deposits and letting-agent statements. Explain deposits, void periods, rent arrears and jointly owned property. Different rules can apply to finance costs, furnished holiday accommodation and property held through a company.','The distinction between a repair and a capital improvement is frequently important. Evidence should describe the condition before the work, what was replaced and whether the asset was improved beyond its original standard. A single contractor invoice labelled “renovation” may not establish the tax treatment. Photographs, surveys, itemised invoices and a clear schedule can produce a more reliable analysis.']},
      {title:'Self-employment income and expense checks',paragraphs:['For a sole trader, HMRC may reconcile declared turnover with invoices, merchant processors, bank deposits, online marketplace records and industry data. Prepare a bridge between gross receipts and the turnover in the return. Identify transfers, loans, capital introduced and other non-trading deposits so they are not mistaken for sales.','Business expenses must normally meet the relevant tax test and private use may need adjustment. Group evidence by expense category and explain the commercial purpose. Mileage, home-working, travel, subsistence and subcontractor costs often require more than a bank statement. Where cash was used, contemporaneous diaries, receipts and supplier confirmations may help establish the amount and purpose.']},
      {title:'Foreign income, assets and data matching',paragraphs:['HMRC receives information through domestic and international reporting systems. A Self Assessment enquiry may ask about overseas bank interest, dividends, pensions, property, trusts or capital gains. A UK resident’s tax position can depend on residence, domicile-related rules, remittance history, double-taxation relief and the source of income. These are specialist areas.','Do not assume that tax paid overseas means nothing is reportable in the UK. Equally, third-party data can be duplicated, incomplete or allocated to the wrong period. Obtain statements and foreign returns, translate key documents where necessary and reconcile currencies using an appropriate method. If omissions exist across several years, consider the correct disclosure route before sending a partial answer.']},
      {title:'Working effectively with your accountant or tax adviser',paragraphs:['Give your adviser the complete HMRC letter, the submitted return, earlier correspondence and a candid account of any concern. Do not filter out documents because they appear unhelpful. A representative needs the unfavourable facts as well as the favourable ones to assess exposure and avoid an inaccurate response. Agree who will speak to HMRC, who will gather records and who has authority to approve letters.','Ask for a written scope and fee basis. Your regular accountant may know the records best, while a tax investigations specialist may lead strategy, interviews or penalty negotiations. The two roles can work together. Review factual statements before submission and correct misunderstandings promptly. Authorising an agent does not remove your responsibility to be truthful, and important deadlines should still be recorded in your own calendar.']},
      {title:'Amendments, interest and penalties',paragraphs:['If HMRC concludes that the return is wrong, it may propose amendments or assessments. Additional tax may attract interest. A separate penalty analysis considers the nature of the inaccuracy, behaviour and disclosure.','Reasonable care is fact-specific. The question is not simply whether an accountant was used but what steps were taken to provide accurate information, query uncertain treatment and review the return. Challenge unsupported assumptions while correcting genuine mistakes.']},
      {title:'How does a Self Assessment enquiry end?',paragraphs:['A formal enquiry normally concludes with a closure notice stating HMRC’s conclusions and any amendment. A taxpayer may in some circumstances apply to the tribunal for a direction that HMRC close an enquiry, although HMRC can resist if it has reasonable grounds to continue.','Check a proposed settlement or closure notice carefully. Confirm the years, tax, interest, penalties and payment consequences. Appeal deadlines can be short. Silence or an informal indication that questions are finished should not be confused with formal closure.']},
      {title:'When professional representation helps',paragraphs:['Seek specialist help where records are incomplete, the enquiry extends beyond one issue, foreign assets or deliberate behaviour are mentioned, HMRC proposes a meeting, or a large adjustment is likely. A tax enquiry specialist can work alongside your usual accountant.','Good representation narrows issues, tests calculations and keeps correspondence moving. It cannot guarantee an outcome, but it can reduce avoidable errors and ensure your evidence is presented coherently.']},
      {title:'Self Assessment enquiry checklist',paragraphs:['Act calmly and methodically. The goal is not to write the longest answer; it is to give HMRC an accurate, evidenced response that addresses the legal and factual issue.'],bullets:['Record the reply deadline','Confirm the tax year and enquiry notice date','Download the submitted return','Preserve all source records','Tell your adviser immediately','Do not guess or alter evidence','Review every response before it is sent']}
    ],
    faqs:[['How far back can HMRC investigate Self Assessment?','The answer depends on whether HMRC uses an ordinary enquiry or discovery powers and on the taxpayer’s behaviour. Different statutory assessment time limits may apply.'],['Does an enquiry mean HMRC thinks I committed fraud?','No. HMRC can open an enquiry without first proving the return is wrong. More serious suspected fraud cases may follow different procedures.'],['Can my accountant deal with the enquiry?','An authorised agent can correspond with HMRC, but you should ensure the factual information supplied is complete and correct.'],['What if I miss the HMRC response deadline?','Contact HMRC promptly, explain the position and obtain advice. Ignoring requests can lead to formal notices, delay and possible penalties.']],
    sources:[['HMRC manual: power to enquire into tax returns','https://www.gov.uk/hmrc-internal-manuals/self-assessment-legal-framework/salf403'],['GOV.UK: Self Assessment general enquiries','https://www.gov.uk/find-hmrc-contacts/self-assessment-general-enquiries']]
  },
  {
    slug:'appeal-hmrc-tax-penalty', category:'General', shortTitle:'HMRC penalties and appeals', keyword:'appeal HMRC penalty', secondaryKeywords:['HMRC penalty appeal','appeal HMRC tax decision','HMRC reasonable excuse appeal'], searchIntent:'Understand the route, evidence and deadline for appealing an HMRC decision or penalty.', reviewed:'23 July 2026', readingTime:'14 min read', updated:'23 July 2026',
    title:'How to Appeal an HMRC Tax Decision or Penalty in the UK',
    description:'Learn how to appeal an HMRC penalty or tax decision, the usual 30-day deadline, statutory reviews, reasonable excuse evidence and tax tribunal steps.',
    intro:['If you disagree with an HMRC tax decision or penalty, acting within the deadline is crucial. The decision letter should explain the appeal route. For many decisions, the usual deadline is 30 days, but the procedure differs between direct and indirect taxes.','An appeal is not a complaint. An appeal challenges whether a tax or penalty decision is correct; a complaint concerns HMRC’s service, such as unreasonable delay or poor conduct. Sending the wrong type of challenge can waste valuable time.','This guide explains the broad UK process, evidence and options. Appeal rights are statutory and decision-specific, so use the instructions in your letter and obtain professional advice where the amount or principle matters.'],
    sections:[
      {title:'Which HMRC decisions can be appealed?',paragraphs:['Many assessments, amendments, penalties and tax decisions carry appeal rights. Examples include an HMRC amendment to a return, a discovery assessment, an inaccuracy penalty, VAT assessment and refusal of certain claims. Not every procedural step is independently appealable.','The notice should identify the legislation, amount, decision date and appeal instructions. Keep the envelope or electronic notification because timing may matter. If the document is unclear, ask HMRC to confirm the decision and appeal right in writing.']},
      {title:'The usual 30-day HMRC appeal deadline',paragraphs:['GOV.UK states that you usually have 30 days from the date of the decision letter to appeal or accept a review, depending on the route. “Usually” matters: check the exact notice and legislation. Do not wait for every supporting document if that risks missing the deadline.','A protective appeal can identify the decision, state that you disagree, give initial grounds and explain that fuller evidence will follow. It must still be genuine and sufficiently clear. Keep proof of submission.']},
      {title:'Direct tax and indirect tax routes',paragraphs:['Direct taxes include Income Tax, PAYE, Corporation Tax, Capital Gains Tax, National Insurance and Inheritance Tax. GOV.UK explains that direct tax decisions are generally appealed to HMRC first. The caseworker reconsiders the matter and may agree, vary or maintain the decision.','For indirect taxes such as VAT, the decision letter commonly offers a statutory review and/or tribunal route. The procedural choices and payment position can differ, so do not reuse an Income Tax appeal template for a VAT dispute without checking it.']},
      {title:'What should an HMRC appeal include?',paragraphs:['A persuasive appeal identifies the decision precisely, sets out each ground and supports factual claims with evidence. Avoid a purely emotional statement that the outcome is unfair. Explain what is wrong and what the correct result should be.','Use a chronology where timing matters. Put calculations in a separate schedule. If relying on reasonable excuse, connect the event directly to the failure and explain what you did to remedy it once the obstacle ended.'],bullets:['Your name or business name','The HMRC reference and decision date','The tax, period and amount','Clear grounds of appeal','The result you say is correct','Supporting documents and calculations','A request for acknowledgement']},
      {title:'Appealing an HMRC penalty on reasonable excuse grounds',paragraphs:['A reasonable excuse depends on all the circumstances. The evidence should show why the obligation was not met and what a reasonable person with your attributes and situation would have done. Simply saying you forgot is unlikely to be enough.','Potentially relevant events may include serious illness, bereavement, unexpected system failure or reliance issues, but labels alone do not win appeals. Provide dates, records, attempts to comply and the date the return or payment was ultimately made.']},
      {title:'HMRC statutory review',paragraphs:['A statutory review is conducted by an HMRC officer who was not involved in the original decision. GOV.UK says reviews usually take 45 days, although the officer will contact you if longer is needed. The review may uphold, vary or cancel the decision.','A review can be quicker and cheaper than tribunal proceedings. It is not always the best strategic option, particularly where a legal issue needs independent determination. Consider the evidence, costs, payment position and whether discussions with the caseworker can resolve matters first.']},
      {title:'Alternative dispute resolution',paragraphs:['HMRC’s Alternative Dispute Resolution process uses a facilitator to help the parties clarify facts and explore agreement. ADR can be useful where communication has stalled or facts are interpreted differently. It is not a substitute for preserving appeal deadlines.','If tribunal notification is required to protect your position, do that first. ADR does not guarantee settlement and may not suit a dispute that turns entirely on a point of law.']},
      {title:'Appealing to the First-tier Tribunal (Tax)',paragraphs:['The First-tier Tribunal is independent of HMRC. For direct tax, you generally need to appeal to HMRC before notifying the tribunal. The tribunal may allocate the case to a category that determines the procedure, evidence and costs approach.','Tribunal litigation requires disciplined pleadings and evidence. Identify the decision under appeal, legal issues, burden of proof and remedy. Directions must be followed. Even where costs are limited, time and professional fees can be substantial.']},
      {title:'Do you have to pay the tax while appealing?',paragraphs:['Payment rules differ. GOV.UK states that a penalty does not generally need to be paid before a tribunal appeal, while tax or duty may remain payable unless postponed or hardship arrangements apply. Interest may continue.','Never assume an appeal automatically suspends collection. Check the decision, request postponement where available and consider Time to Pay separately if affordability is the issue rather than correctness.']},
      {title:'Late appeals',paragraphs:['If the deadline has passed, act immediately. Explain the delay fully and submit the underlying grounds. HMRC or the tribunal may consider a late appeal, but permission is not automatic. The longer the delay, the more compelling and evidenced the explanation generally needs to be.','Do not spend weeks perfecting the explanation while delay continues. Obtain advice, submit the appeal and gather supporting records promptly.']},
      {title:'Building an evidence file for an appeal',paragraphs:['Create one indexed appeal file containing the decision, correspondence, relevant returns, calculations, contracts and supporting records. Add a chronology that links each event to an exhibit. Evidence should prove the facts relied on rather than overwhelm the reviewer. Ten relevant documents with clear explanations are often more useful than hundreds of unsorted pages.','Witness evidence may be necessary where events are not recorded elsewhere. Write a factual statement in date order while memories are fresh, distinguishing what the witness saw from what they were told. Preserve electronic originals and metadata where relevant. If expert evidence or valuation is needed, clarify the question the expert must answer and ensure the methodology is transparent.']},
      {title:'How to write effective grounds of appeal',paragraphs:['Grounds of appeal are the reasons the decision is wrong. Separate each ground under a short heading and connect it to the facts, law and requested correction. For a calculation dispute, provide the alternative calculation. For a penalty, address the underlying failure, behaviour, disclosure, reasonable excuse or proportionality point that the legislation permits.','Avoid arguing every conceivable point. Weak arguments can obscure strong ones and increase cost. Do not make allegations about an officer’s motives unless genuinely relevant and evidenced. A professional formulation might say that HMRC relied on an incorrect factual assumption, identify that assumption, cite the evidence disproving it and state the resulting adjustment.']},
      {title:'Costs, risk and settlement decisions',paragraphs:['Before escalating, compare the tax at stake, prospects, professional fees, management time, interest exposure and wider precedent. Tribunal cases can create public decisions and require disclosure of evidence. A principled case may justify litigation, but a commercial settlement can sometimes resolve uncertainty more efficiently where the law and facts permit.','Any settlement should specify the taxes, periods, figures, penalties, payment dates and whether it resolves all issues. Do not withdraw an appeal on an informal assurance that is not recorded. If an offer is made “without prejudice” or under a formal settlement process, understand the legal effect and who has authority to accept it. Independent advice is particularly valuable before giving up appeal rights.']},
      {title:'What happens after the appeal decision?',paragraphs:['If HMRC accepts the appeal or a review cancels the decision, ask for written confirmation and check that the account, interest and collection position are corrected. If the decision is varied, reconcile the revised figures and payment date. A successful appeal against a penalty does not necessarily remove the underlying tax or interest, while a tax adjustment may require consequential amendments to other periods or company records.','After a tribunal decision, further appeal rights are generally limited to errors of law and involve additional procedure and deadlines. Obtain advice quickly before seeking permission to appeal. If the case ends, retain the indexed file and record any changes needed to tax processes, software, record retention or adviser review. The most useful outcome is not only resolving the notice but reducing the chance of the same issue recurring.']},
      {title:'Common appeal mistakes',paragraphs:['Weak appeals miss deadlines, challenge the wrong decision, omit evidence, confuse complaint and appeal, or focus on hardship when the legal question is whether the decision is correct. Another mistake is accepting a review without diarising the next deadline.'],bullets:['Waiting for HMRC to telephone back','Sending an appeal to the wrong address','Failing to retain proof of delivery','Using generic reasonable-excuse wording','Ignoring tax collection during the dispute','Missing the tribunal deadline after review']},
      {title:'A practical appeal plan',paragraphs:['Start with the notice, deadline and desired outcome. Preserve the right of appeal, then build the evidence and legal analysis. Keep communications professional and propose a clear correction. A strong appeal makes it easy for the reader to understand both the problem and the remedy.']}
    ],
    faqs:[['Can I appeal an HMRC penalty online?','Some penalties have online appeal routes, while others require a form or written appeal. Follow the instructions on the decision letter and GOV.UK service for that penalty.'],['How long does an HMRC appeal take?','It varies. GOV.UK says statutory reviews usually take 45 days, while negotiations or tribunal proceedings can take considerably longer.'],['Is financial hardship a reason to cancel a penalty?','Hardship and reasonable excuse are different questions. Hardship may be relevant to payment arrangements but does not automatically make a penalty legally incorrect.'],['Can an accountant represent me at tribunal?','Tax advisers and legal advisers may assist, subject to their competence and the tribunal’s rules. Choose someone with relevant dispute experience.']],
    sources:[['GOV.UK: Disagree with a tax decision','https://www.gov.uk/tax-appeals/decision'],['GOV.UK: Get a statutory review','https://www.gov.uk/tax-appeals/review-of-a-tax-or-penalty-decision'],['GOV.UK: Appeal to the tax tribunal','https://www.gov.uk/tax-tribunal']]
  }
];

export const guides: Guide[] = [...coreGuides, ...extraGuides, ...latestGuides].map(expandGuide);
export const categories = ['Individual','Business','General'] as const;
