import type { Guide } from './guides';

const common = {readingTime:'11 min read',updated:'17 July 2026',reviewed:'Official guidance checked 17 July 2026'};

export const latestGuides: Guide[] = [
  {
    ...common,slug:'hmrc-use-of-home-expenses-enquiry',category:'Individual',shortTitle:'Use of home expense checks',
    keyword:'HMRC use of home expenses enquiry',secondaryKeywords:['use of home as office HMRC','working from home tax expenses check','HMRC home office expenses questions','simplified expenses use of home'],searchIntent:'How HMRC checks business or employment homeworking expense claims and which records support them.',
    title:'HMRC Use of Home Expenses Enquiry: Questions and Evidence',
    description:'Learn how HMRC checks use-of-home expenses, which records support a claim and how the rules differ for sole traders, employees and company directors.',
    intro:['An HMRC use of home expenses enquiry checks whether a deduction or tax-free payment for working at home follows the rules that apply to that taxpayer. A self-employed trader, employee and company director should not apply the same test automatically.','For a sole trader, HMRC’s Business Income Manual explains actual-cost apportionment and optional simplified expenses. Employee and director rules are dealt with separately in the Employment Income Manual, including revised guidance for treatment from 6 April 2026.','This guide explains likely evidence and questions. It does not decide whether a particular room, payment or household cost qualifies.'],
    sections:[
      {title:'Which use-of-home rules apply?',paragraphs:['HMRC will first identify who incurred or reimbursed the cost and in what capacity. A sole trader may consider a business proportion of actual household costs or, where eligible, simplified expenses. Employees and directors face the employment-expense and exemption rules applicable to the period. A company paying rent to a director can raise additional contractual, benefit, property-income and company-deduction questions.']},
      {title:'Questions HMRC may ask',paragraphs:['The officer may ask what work was performed at home, why it was necessary, which rooms were used, for how long, how the amount was calculated and whether the employer provided facilities. Questions should relate to the tax position and period being checked.'],bullets:['Who paid each household bill?','Was the space used exclusively or also privately?','How many rooms and business-use hours were used in the calculation?','Was a flat rate or actual-cost method claimed?','Did an employer reimburse any amount?','Is there a rental or licence agreement with a company?']},
      {title:'Evidence for a self-employed claim',paragraphs:['Keep bills, floor-area or room calculations, usage records and the filed computation. HMRC manual guidance allows a reasonable apportionment where an identifiable part is incurred wholly and exclusively for the trade. The method should reflect the facts and be applied consistently rather than reverse-engineered to reach a preferred figure.']},
      {title:'Simplified expenses and the 25-hour threshold',paragraphs:['HMRC’s current manual says the optional flat rate for household running costs is based on hours spent wholly and exclusively on core business activities at home and is available when those hours exceed 25 per month. Fixed costs can require a separate actual-business-use analysis. Check the rates and eligibility for the relevant tax year.']},
      {title:'Employees and directors from 6 April 2026',paragraphs:['HMRC’s pre-6 April 2026 employment guidance now points to separate guidance for later periods. That makes the date and whether the claim is an employee deduction or employer payment essential. Do not rely on an older homeworking article or assume personal choice to work at home satisfies the statutory test.']},
      {title:'Exclusive business use and Capital Gains Tax',paragraphs:['A room used exclusively for business can affect private residence relief when the home is sold. Mixed domestic use may change the analysis. The enquiry response should describe actual use accurately rather than changing the description solely to obtain an income-tax deduction.']},
      {title:'How to answer the enquiry',paragraphs:['Provide a short factual description, calculation, bills and reconciliation to the return. Identify any estimate and its basis. If the HMRC question combines company, employment and self-employment rules, separate the answers and ask the officer to confirm the relevant tax treatment.']}
    ],
    faqs:[['What proof does HMRC require for working-from-home expenses?','Relevant evidence can include bills, calculations, room or floor-area information, business-use records, employment terms and reimbursement records. The evidence depends on the claim.'],['Can a sole trader claim a room as an office?','A reasonable business proportion of eligible costs or simplified expenses may be available, subject to the applicable conditions and evidence.'],['Can a director charge rent to their company?','A genuine arrangement can create company, personal property-income and other consequences. It should be documented and reviewed rather than treated as a simple expense claim.'],['Will using a room as an office affect Capital Gains Tax?','Exclusive business use can affect private residence relief. Mixed use and the precise facts matter.'],['Did employee homeworking rules change in 2026?','HMRC’s manual separates treatment before 6 April 2026 from guidance applying from that date, so the period must be checked.']],
    sources:[['HMRC Business Income Manual: use of home','https://www.gov.uk/hmrc-internal-manuals/business-income-manual/bim47800'],['HMRC Business Income Manual: simplified use-of-home expenses','https://www.gov.uk/hmrc-internal-manuals/business-income-manual/bim75010'],['HMRC Employment Income Manual: homeworking before 6 April 2026','https://www.gov.uk/hmrc-internal-manuals/employment-income-manual/eim32760']]
  },
  {
    ...common,slug:'hmrc-management-fees-enquiry',category:'Business',shortTitle:'Management fee enquiries',
    keyword:'HMRC management fees enquiry',secondaryKeywords:['management fees tax deductible UK','intercompany management charges HMRC','management fee supporting evidence','wholly and exclusively management fees'],searchIntent:'How HMRC tests management charges and what commercial, contractual and calculation evidence is required.',
    title:'HMRC Management Fees Enquiry: Deductibility and Evidence',
    description:'Understand how HMRC may examine management fees, intercompany charges and investment management expenses, including contracts, services, pricing and evidence.',
    intro:['An HMRC management fees enquiry may ask whether services were actually supplied, who benefited, how the charge was calculated and whether the payer’s tax rules permit a deduction. An invoice and accounting entry are evidence, but they do not settle those questions.','For a trading company, the wholly and exclusively test and other restrictions can apply. For an investment company claiming expenses of management, HMRC’s Company Taxation Manual says the statutory test is whether the expense is an expense of managing the investment business; it is not simply the trading test under another name.','Cross-border or connected-party charges may also require transfer-pricing, withholding-tax, VAT and permanent-establishment analysis. This guide focuses on enquiry evidence.'],
    sections:[
      {title:'What HMRC may be checking',paragraphs:['The officer may test commercial purpose, recipient, services, timing, amount, duplication and whether the fee is revenue or capital. Connected-party fees can receive close scrutiny where one entity has losses, a lower tax rate or little evidence of staff performing the work. These features do not decide the outcome by themselves.']},
      {title:'Likely HMRC questions',paragraphs:['Expect questions that connect the written agreement to the people, work and benefit in the period. Answers should be supported by contemporaneous records.'],bullets:['What services were contracted and delivered?','Who performed them and when?','How was the fee or allocation key calculated?','Why did the payer need the services?','Were costs duplicated elsewhere?','How were VAT and any cross-border obligations treated?']},
      {title:'Contracts, invoices and delivery evidence',paragraphs:['Keep signed agreements, invoices, board approvals, work logs, reports, emails and evidence of payment. Generic wording such as “management services” is weaker than a schedule linking deliverables, personnel and calculation to the accounting period. A retrospective agreement should never be presented as contemporaneous.']},
      {title:'Trading-company deduction',paragraphs:['HMRC’s Business Income Manual identifies the statutory prohibition for expenses not incurred wholly and exclusively for the trade. The enquiry should analyse the payer’s purpose, any non-trade benefit, capital features and specific statutory restrictions. A reasonable apportionment is only available where the law and facts identify a separable qualifying part.']},
      {title:'Investment-company management expenses',paragraphs:['HMRC manual guidance states that CTA 2009 section 1219 does not contain the same wholly and exclusively wording; the question is whether the expense is an expense of managing the investment business. The amount must still satisfy the correct statutory criterion, and excessive director remuneration or shareholder benefit may be challenged on the facts.']},
      {title:'Intercompany pricing and allocations',paragraphs:['Explain the cost pool, exclusions, allocation key, mark-up and recipient benefit. Headcount, turnover, time or transactions can be sensible drivers only when they reflect the service. Preserve the group policy and calculations used at the time.']},
      {title:'Responding to HMRC',paragraphs:['Separate each fee, entity and period. Provide a reconciliation from provider costs to invoice and from invoice to the payer’s ledger and tax computation. State clearly which deduction rule is relied on and address VAT or international issues separately.']}
    ],
    faqs:[['Are management fees automatically tax deductible?','No. The applicable statutory test, facts, purpose, services and any restrictions must be considered.'],['Is an invoice enough evidence?','Usually not by itself. HMRC may ask for the agreement, actual services, calculation, benefit and payment evidence.'],['Can a parent company charge subsidiaries?','It can charge for genuine services, but the recipient benefit, allocation and any transfer-pricing or VAT rules need analysis.'],['Do investment-company management expenses use the wholly and exclusively test?','HMRC says the section 1219 criterion is whether the expense is an expense of managing the investment business, not the trading test itself.'],['Can HMRC disallow an excessive fee?','HMRC may challenge whether all or part satisfies the relevant rule, including where evidence does not support the services or amount.']],
    sources:[['HMRC Business Income Manual: wholly and exclusively','https://www.gov.uk/hmrc-internal-manuals/business-income-manual/bim37035'],['HMRC Company Taxation Manual: management expenses','https://www.gov.uk/hmrc-internal-manuals/company-taxation-manual/ctm08170'],['HMRC International Manual: transfer pricing','https://www.gov.uk/hmrc-internal-manuals/international-manual/intm410000']]
  },
  {
    ...common,slug:'hmrc-overdrawn-directors-loan-account-enquiry',category:'Business',shortTitle:'Overdrawn director loan accounts',
    keyword:'overdrawn director loan account HMRC enquiry',secondaryKeywords:['director loan account tax implications','section 455 tax director loan','beneficial loan benefit in kind','director loan bed and breakfasting'],searchIntent:'What happens when HMRC checks an overdrawn director’s loan account and how section 455, benefits and repayments are reviewed.',
    title:'Overdrawn Director’s Loan Account: HMRC Enquiry Implications',
    description:'A 2026 guide to HMRC checks of overdrawn director loan accounts, section 455 tax, beneficial loans, repayments, write-offs and bed-and-breakfasting rules.',
    intro:['A director’s loan account is overdrawn when a director or participator owes money to the company after all relevant credits and debits are recorded. HMRC may check the ledger, bank transactions, expenses, dividends, salary entries and repayments.','For a close company, an outstanding loan can create a temporary Corporation Tax charge under section 455. Separate employment-tax consequences may arise under the beneficial-loan rules, and a release or write-off can create further tax and National Insurance questions.','The balance-sheet figure alone is not enough. The transaction dates, borrower, capacity, repayment timing and later withdrawals must be reconstructed.'],
    sections:[
      {title:'Questions HMRC may ask about the loan account',paragraphs:['HMRC may ask for the full account, bank statements, nominal-ledger detail, expense claims, dividend paperwork, payroll records and evidence of repayment. It may test whether personal expenditure was posted elsewhere or whether credits were legally effective.'],bullets:['Who received each payment or benefit?','Was the transaction salary, dividend, expense reimbursement or loan?','Was the company solvent when a dividend was declared?','What balance remained nine months after the period end?','Were repayments followed by new advances?','Was interest paid at an adequate rate?']},
      {title:'Section 455 company tax charge',paragraphs:['The close-company loan rules can impose a company tax charge where a loan to a participator or associate remains outstanding after the statutory period. It is not the director’s personal repayment of the loan and it does not make the extraction tax-free. Use the rate and rules for the relevant period.']},
      {title:'Beneficial-loan employment tax',paragraphs:['A cheap or interest-free loan can be a taxable benefit where the statutory conditions are met. Check the balance method, official rate, exemptions, P11D treatment and Class 1A National Insurance separately from section 455.']},
      {title:'Repayment and relief',paragraphs:['A genuine repayment or release can affect section 455 relief, but claims and timing rules apply. Trace the funds and board or payroll treatment. Merely crediting an unsupported salary, bonus or dividend entry may not establish an effective repayment.']},
      {title:'Bed-and-breakfasting rules',paragraphs:['HMRC’s 2026 manual explains a 30-day matching rule where repayments and new loans of at least £5,000 occur in the relevant conditions. A separate arrangements rule can also be relevant. Temporary repayment followed by re-borrowing should be disclosed and analysed, not omitted from the chronology.']},
      {title:'Write-off or release',paragraphs:['Writing off a loan does not simply erase the tax position. Income tax, National Insurance, company-law and accounting consequences can arise according to the borrower and circumstances. Obtain advice before approving or reporting a release.']},
      {title:'Preparing the enquiry response',paragraphs:['Create a daily transaction schedule from the ledger and bank records, label the legal nature of each credit, calculate balances at relevant dates and reconcile the statutory accounts and Company Tax Return. Address section 455, benefit reporting and later relief as separate workstreams.']}
    ],
    faqs:[['Is an overdrawn director’s loan illegal?','Not automatically, but company-law approvals, solvency, tax and reporting consequences need to be checked.'],['When does section 455 tax arise?','It can arise for a close company where a relevant participator loan remains outstanding beyond the statutory post-period deadline.'],['Is section 455 paid by the director?','The charge is imposed on the company; the director still owes the loan unless it is validly repaid, released or otherwise dealt with.'],['Can a dividend clear the loan?','Only a lawful, properly documented dividend to the relevant shareholder can create the intended credit, and tax consequences remain.'],['Does repaying and immediately borrowing again work?','Anti-avoidance matching rules can apply, including the 30-day rule described in HMRC’s manual.']],
    sources:[['GOV.UK: Director’s loans','https://www.gov.uk/directors-loans'],['HMRC Company Taxation Manual: 30-day rule','https://www.gov.uk/hmrc-internal-manuals/company-taxation-manual/ctm61630'],['HMRC Director’s Loan Accounts Toolkit','https://www.gov.uk/government/publications/directors-loan-accounts-toolkit']]
  },
  {
    ...common,slug:'companies-house-accounts-vs-hmrc-tax-return',category:'Business',shortTitle:'Companies House and HMRC accounts',
    keyword:'Companies House accounts vs HMRC tax return',secondaryKeywords:['Companies House and HMRC different deadlines','company accounts mismatch HMRC','file company accounts 2026','Company Tax Return accounts difference'],searchIntent:'Why Companies House accounts and HMRC filings differ, which deadlines apply and how mismatches may be explained during an enquiry.',
    title:'Companies House Accounts vs HMRC Tax Return: Enquiry Risks',
    description:'Understand the difference between Companies House accounts and an HMRC Company Tax Return, 2026 filing routes, deadlines and how to explain mismatches.',
    intro:['Companies House annual accounts and an HMRC Company Tax Return are connected but separate filings with different legal purposes, deadlines and content. Statutory accounts accompany the tax return, while the return also includes tax computations and company-specific declarations.','A difference between public Companies House information and the HMRC computation is not automatically an error. Filing exemptions, tax adjustments, different periods and first-year rules may explain it. Unreconciled figures, however, can prompt questions.','The joint online service closed on 31 March 2026. Current filing methods and future reforms should be checked directly on GOV.UK.'],
    sections:[
      {title:'Companies House and HMRC deadlines',paragraphs:['GOV.UK currently states that a private company normally files annual accounts nine months after the financial year end, pays Corporation Tax nine months and one day after the accounting period, and files the Company Tax Return within 12 months. First accounts and unusual periods have different rules.']},
      {title:'Why the filings contain different figures',paragraphs:['Accounting profit is adjusted for tax: disallowable expenses, capital allowances, losses, group relief and other rules can change taxable profit without changing statutory accounting profit. Small or micro-entity public accounts may also contain less visible detail than the accounts supplied with the tax return.']},
      {title:'Questions HMRC may ask',paragraphs:['HMRC may request a bridge from accounts to taxable profit, the full tagged accounts, trial balance, amended versions and explanations for period or comparative differences.'],bullets:['Do both filings use the same approved accounts?','Were accounts amended after one filing?','Why does turnover differ from VAT or payroll data?','Do director balances agree across records?','Were tax adjustments supported?','Were two returns needed for a long first accounting period?']},
      {title:'First accounts and accounting periods',paragraphs:['Companies House first accounts can cover more than 12 months, while a Corporation Tax accounting period cannot normally exceed 12 months. GOV.UK explains that two tax returns may therefore be needed. Build a date map before assuming a period is missing.']},
      {title:'2026 filing change',paragraphs:['Companies House guidance states that the online service previously used to file accounts and a Company Tax Return closed on 31 March 2026. Businesses should use current compatible routes and should not follow older tutorials that direct them to the closed service.']},
      {title:'Late filing and penalties',paragraphs:['Companies House and HMRC penalties are separate. Filing with one body does not satisfy the other. If an exceptional event threatens Companies House filing, an extension application must be made before the deadline under the published process.']},
      {title:'Enquiry response and reconciliation',paragraphs:['Provide approved accounts, filing receipts, tax computations and a one-page reconciliation of every difference. If a filing is wrong, identify the correction process and coordinate amendments so Companies House, HMRC and internal records do not diverge further.']}
    ],
    faqs:[['Are Companies House accounts the same as a Company Tax Return?','No. Statutory accounts form part of the HMRC submission, but the tax return and computations contain additional tax information.'],['Why can Companies House profit differ from taxable profit?','Corporation Tax rules adjust accounting profit for disallowable costs, reliefs, allowances and other items.'],['What are the normal private-company deadlines?','GOV.UK currently lists nine months for annual accounts, nine months and one day to pay Corporation Tax, and 12 months for the Company Tax Return, subject to exceptions.'],['Can I still file accounts and the tax return using the old joint online service?','Companies House says that service closed on 31 March 2026; use a current approved filing route.'],['Does filing at Companies House notify HMRC?','Do not assume it satisfies HMRC filing or notification obligations; the regimes are separate.']],
    sources:[['GOV.UK: Accounts and tax return deadlines','https://www.gov.uk/prepare-file-annual-accounts-for-limited-company/overview'],['Companies House: filing accounts guidance','https://www.gov.uk/government/publications/life-of-a-company-annual-requirements/life-of-a-company-part-1-accounts'],['GOV.UK: First accounts and Company Tax Return','https://www.gov.uk/first-company-accounts-and-return/overview']]
  },
  {
    ...common,slug:'dormant-company-companies-house-hmrc',category:'Business',shortTitle:'Dormant company status',
    keyword:'dormant company Companies House and HMRC',secondaryKeywords:['dormant company tax return','tell HMRC company is dormant','dormant company accounts Companies House','can a dormant company receive money'],searchIntent:'How dormant status differs for Companies House and Corporation Tax, what can end dormancy and what records HMRC may check.',
    title:'Dormant Company: Companies House and HMRC Rules Explained',
    description:'A 2026 guide to dormant-company status for Companies House and HMRC, filing duties, transactions that may end dormancy and enquiry evidence.',
    intro:['A company can be dormant for Companies House purposes, Corporation Tax purposes, both or neither. The definitions and filing consequences are not identical, so a dormant-accounts filing does not by itself settle the HMRC position.','GOV.UK says a company is usually dormant for Corporation Tax if it has not started trading, has stopped trading with no other income, or meets another listed circumstance. Activities such as trading or receiving interest can affect that status.','Directors should review every bank and ledger transaction before stating that a company was dormant.'],
    sections:[
      {title:'Dormant for Corporation Tax',paragraphs:['HMRC considers whether the company is active for Corporation Tax. GOV.UK examples of activity include buying, selling, renting property, advertising, employing someone or receiving interest. The precise facts and any notice to file must be checked.']},
      {title:'Dormant for Companies House',paragraphs:['Companies House dormancy is based on whether there have been significant accounting transactions, subject to defined exceptions. A company may still have to file dormant accounts and a confirmation statement.']},
      {title:'Transactions HMRC may question',paragraphs:['An enquiry or status check may ask about bank interest, sales, purchases, expenses, assets, payroll, VAT, director payments and preparatory activity.'],bullets:['Bank credits and interest','Invoices issued or received','Website, advertising and customer activity','Employee or director remuneration','Property rent or investment income','VAT registration and returns']},
      {title:'Telling HMRC the company is dormant',paragraphs:['GOV.UK explains how to notify HMRC when a company has stopped trading and has no other income. If HMRC has issued a notice to deliver a Company Tax Return, the company may still need to file for that period unless HMRC withdraws the notice.']},
      {title:'Companies House filings continue',paragraphs:['Dormant companies generally continue to file annual accounts and confirmation statements. Missing these obligations can lead to penalties or strike-off action even where no Corporation Tax is due.']},
      {title:'VAT and PAYE consequences',paragraphs:['GOV.UK states that a company not intending to trade again should address VAT deregistration and PAYE closure, while a company intending to restart may have continuing nil-return duties. Check the current instructions for each registration.']},
      {title:'Restarting and responding to HMRC',paragraphs:['Record the date activity restarted, register or reactivate Corporation Tax obligations as required and preserve opening transactions. If HMRC challenges dormancy, provide the bank statements, ledger and explanation of each transaction rather than relying only on the Companies House filing label.']}
    ],
    faqs:[['Is dormant status the same for Companies House and HMRC?','No. The definitions and obligations differ, so both positions must be checked.'],['Must a dormant company file Companies House accounts?','Usually yes, along with a confirmation statement, unless a specific exemption applies.'],['Does a dormant company file a Company Tax Return?','Once HMRC accepts Corporation Tax dormancy, further returns may not be required unless HMRC issues a notice; an existing notice generally still needs dealing with.'],['Can a dormant company receive bank interest?','Interest can affect Corporation Tax dormancy. Review the amount and facts rather than assuming it is irrelevant.'],['Can HMRC check a company marked dormant at Companies House?','Yes. HMRC can examine whether the company was active for tax and may request records.']],
    sources:[['GOV.UK: Dormant for Corporation Tax','https://www.gov.uk/dormant-company/dormant-for-corporation-tax'],['GOV.UK: Dormant companies and Companies House','https://www.gov.uk/dormant-company/dormant-for-companies-house'],['GOV.UK: Restarting a dormant company','https://www.gov.uk/restart-a-non-trading-or-dormant-company']]
  }
];
